### ISSUE TITLE
Documentation use client name that were not defined

### ISSUE THREAD

**Issue by krzysztof-alboszta** [snc/SncRedisBundle#163]
in section about session configuration the config examples use `client: session` which is not used anywhere else in docs especially in full config example. For more readability it should be `default` client

```
snc_redis:
    ...
    session:
        client: session
```
