### ISSUE TITLE
[1.1.8] Different Clients injected for snc_redis.default[_client]

### ISSUE THREAD

**Issue by pminnieur** [snc/SncRedisBundle#170]
With the following configuration, I get different clients injected with the `snc_redis.default[_client]` service id with the bundle version `1.1.8`:

``` yaml
snc_redis:
    clients:
        default:
            type:    phpredis
            alias:   default
            dsn:     "%redis_dsn%/0"
            logging: %kernel.debug%
```

In `dev` environment the client is an instance of `Snc\RedisBundle\Client\Phpredis\Client` but in `prod` environment its an instance of `\Redis`. I guess that's not how it should work, right?
