### ISSUE TITLE
Master-Slave Doctrine Cache

### ISSUE THREAD

**Issue by The-Don-Himself** [snc/SncRedisBundle#198]
First, lovely bundle.

Not an issue but a question, average Symfony user here meaning I cannot handle extremely complex code and configurations yet. 

I have set up 1 Redis master with 3 geographically slaves. I use redis for caching doctrine queries using Query Builder eg.
$em = $this->getDoctrine()->getManager();
$query = $em
	->getRepository('MyBundle:MyEntity')
	->createQueryBuilder('q')
	->select('q')
	->getQuery()
	->useResultCache(true, 3600, 'my_unique_query_id')
	->getOneOrNullResult();

Question is, if possible, how can I setup the bundle such that the above query will read from a slave for cached data and if absent query the db and save to the master which replicates to the slaves.

I know I this is possible, and I can manually modify all my code to do this but the question is can the bundle take care of this through the master-slave configurations or is that mainly for sessions et all?

**Comment by snc** [comment]
You can find the following in the docs:

A setup using `predis` master-slave replication could look like this:

``` yaml
snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn:
                - redis://master-host?alias=master
                - redis://slave-host1
                - redis://slave-host2
            options:
                replication: true
```
Choosing a slave instead of master should be handled by predis then.
