### ISSUE TITLE
Doctrine Second Level Cache [SOLVED!]

### ISSUE THREAD

**Issue by The-Don-Himself** [snc/SncRedisBundle#216]
As always, I must complement the devs on a fantastic bundle, will never get tired of saying it.

Question : 
If possible, how can we use this bundle to activate and store doctrine second level cache? Tried many configuration guesses but none have worked e.g this link http://www.ekreative.com/blog/three-symfony2-database-optimisation-tips-to-implement-today/468-three-symfony2-database-optimisation-tips-to-implement-today

**Comment by The-Don-Himself** [comment]
Does anyone know whether this bundle is compatible with doctrine second level cache? Activating it with redis results in no cache hit put logs does show cache puts. Switching to memcache or apc works but wouldn't it be great to keep everything in redis:)
Ping @nrk

**Comment by nrk** [comment]
Sorry @The-Don-Himself but I'm not familiar with the combination of this bundle with Doctrine, I'm just the maintaner of one of the underlying libraries (Predis) used by SncRedisBunlde. You should wait for @snc to give you a better insight of how things work in your use case.

**Comment by The-Don-Himself** [comment]
@nrk Apologies for the confusion but thanks for responding, fyi Predis rocks!

**Comment by PouleR** [comment]
I'm also struggling with the second_level_cache, however I managed to get it working. The results are stored in Redis and after they are expired they are retrieved from the database again.

However, I'm using multiple Redis DB's, in this case one specific for Doctrine (And for e.g. sessions in another Redis DB). The problem is that the result cache is written to the default Redis DB and not (in this case DB 11)

How can I configure SncRedis / Doctrine to use a separate DSN for this?

config.yml:
```
orm:
    entity_managers:
        default:
            second_level_cache:
                region_cache_driver:
                    type: redis
                enabled: true

snc_redis:
    clients:
        default:
            type: phpredis
            alias: default
            dsn: redis://localhost
        doctrine_redis:
            type: phpredis
            alias: doctrine_redis
            dsn: redis://localhost/11
    doctrine:
        metadata_cache:
            client: doctrine_redis
            entity_manager: default
            document_manager: default
            namespace: "%kernel.root_dir%"
        result_cache:
            client: doctrine_redis
            entity_manager: default
            namespace: "%kernel.root_dir%"
        query_cache:
            client: doctrine_redis
            entity_manager: default
            namespace: "%kernel.root_dir%"
```

Entity.php
```
* @ORM\Cache(usage="READ_ONLY", region="region_entity")
```

EntityRepository.php
```
->getQuery()
->setCacheable(true)
->setLifetime(60)
->useResultCache(true, 60)
->getResult();
```

**Comment by snc** [comment]
I've never used this doctrine feature, but with your config above, doctrine does not use anything from the redis bundle. Is it possible to pass a service there?

**Comment by The-Don-Himself** [comment]
@PouleR trust me, I have tried for over a month and this is just not possible currently with SncRedisBundle.
I also tried your config above and it works but not using the redis bundle so it is deceiving you just as @snc has stated it goes to redis directly which is probably not what you want for a distributed cache system.

**Comment by Pouix** [comment]
@The-Don-Himself @PouleR You can create a Redis driver service the same way SncRedisBundle:

services.yml
```yaml
services:
    snc_second_level_cache:
        class: %snc_redis.doctrine_cache.class%
        calls:
            - ["setRedis", ["@snc_redis.doctrine_redis"]]
            - ["setNamespace", ["DoctrineSecondLevelCache"]]
```
config.yml
```yaml
orm:
    entity_managers:
        default:
            second_level_cache:
                region_cache_driver:
                    type: service
                    id: snc_second_level_cache
                enabled: true

snc_redis:
    clients:
        default:
            type: phpredis
            alias: default
            dsn: redis://localhost
        doctrine_redis:
            type: phpredis
            alias: doctrine_redis
            dsn: redis://localhost/11
    doctrine:
        metadata_cache:
            client: doctrine_redis
            entity_manager: default
            document_manager: default
            namespace: "%kernel.root_dir%"
        result_cache:
            client: doctrine_redis
            entity_manager: default
            namespace: "%kernel.root_dir%"
        query_cache:
            client: doctrine_redis
            entity_manager: default
            namespace: "%kernel.root_dir%"
```
