### ISSUE TITLE
Call to a member function wakeupReflection() on a non-object

### ISSUE THREAD

**Issue by samplenull** [snc/SncRedisBundle#217]
After switching to Redis (php5-redis with SncRedisBundle) for doctrine metadata and query cache, I have this error
Fatal Error (E_ERROR): Call to a member function wakeupReflection() on a non-object in vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:721

I'd appreciate some help.
my config:

```
snc_redis:
    # configure predis as client
    clients:
        default:
            type: phpredis
            alias: default
            dsn: redis://localhost
            loggable:
        doctrine:
            type: phpredis
            alias: doctrine
            dsn: redis://localhost
    # configure doctrine caching
    doctrine:
        metadata_cache:
            client: doctrine
            entity_manager: default
            document_manager: default
        result_cache:
            client: doctrine
            entity_manager: [default]
        query_cache:
            client: doctrine
            entity_manager: default
```
