### ISSUE TITLE
strlen() expects parameter 1 to be string, array given in RedisSessionHandler lockSession

### ISSUE THREAD

**Issue by qwebot** [snc/SncRedisBundle#235]
I have a problem. My config looks like this:
```yaml
snc_redis:
    clients:
        session:
            type: predis
            alias: session
            logging: false
            dsn: redis://localhost
        cache:
            type: predis
            logging: false
            alias: cache
            dsn: redis://localhost/1
    session:
        client: session
        ttl: 86000
        prefix: foo
        use_as_default: true
```

without description doctrine part. So, in this case there is a warning in lockSession method RedisSessionHandler class. When it call $this->redis->set(..) the third argument is array('NX', 'PX' => $this->lockMaxWait * 1000 + 1) , but it must be a string.
