### ISSUE TITLE
Clearing Doctrine cache does not really deleting the keys

### ISSUE THREAD

**Issue by hehachris** [snc/SncRedisBundle#239]
When running `app/console doctrine:cache:clear-*`, it will only increment the value in `DoctrineNamespaceCacheKey` but not deleting the keys. While the old keys did not have TTL set,  they will remain on Redis server forever.

My current workaround is to create a custom command to deleting the keys with the namespace prefix. Any other suggestions?

**Comment by Pouix** [comment]
@hehachris You could use a dedicated redis instance for the Cache and let Redis manage key eviction by itself.

- set a ```maxmemory``` limit.
- set ```maxmemory-policy``` to ```allkeys-lru```.
- set ```maxmemory-samples``` to ```5``` (or ```10``` if you want it to be more accurate but it will cost more CPU too).

When you'll reach the max memory limit, Redis will try to remove the less recently used (LRU) keys first.
With this configuration, you don't need to set any TTL on Doctrine caches.

[Using Redis as an LRU cache](http://redis.io/topics/lru-cache)

**Comment by snc** [comment]
Which version of the bundle are you using?

**Comment by trousers** [comment]
I'm looking for a solution to this also, when running composer update 

"Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache"

does not delete the keys (using bundle version 1.1)

**Comment by Pouix** [comment]
@trousers On 1.1 version, clients aren't defined as tagged service.
You can use a custom CacheClearer:
```php
<?php
namespace AppBundle\Cache;

use Symfony\Component\HttpKernel\CacheClearer\CacheClearerInterface;

class RedisClearer implements CacheClearerInterface
{
    private $clients = array();
    
    /**
     * Constructor
     *
     * @param array<\Predis\Client|\Redis> array of SNC Redis clients
     */
    public function __construct($clients)
    {
        if (false === is_array($clients)) {
            $clients = array($clients);
        }
        $this->clients = $clients;
    }
    
    /**
     * Clear your cache
     */
    public function clear($cacheDir)
    {
        foreach ($this->clients as $client) {
            if ($client instanceof \Redis || $client instanceof \Predis\ClientInterface) {
                $client->flushDb();
            }
        }
    }
}
```

And set up the service:
```yaml
services:
    myapp.redis_clearer:
        class: AppBundle\Cache\RedisClearer
        arguments:
        # Put all the SNC Redis client you want to clear (Example: defaults and dbslc clients)
            - [ "@snc_redis.default_client", "@snc_redis.dbslc_client" ]
        tags:
            - { name: kernel.cache_clearer }
```

That works with `php app/console cache:clear` and `Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache`.

On the master branch, you can set up a Compiler Pass, list all clients with `snc_redis.client`.
