### ISSUE TITLE
Master slave connection but it store into one db when putting data

### ISSUE THREAD

**Issue by vortexgin** [snc/SncRedisBundle#245]
I have snc configuration like this 
```
snc_redis:
    clients:
        session:
            type: predis
            alias: session
            dsn:
                - %redis.host.master%/%redis.client.session%?alias=master
                - %redis.host.slave1%/%redis.client.session%
                - %redis.host.slave2%/%redis.client.session%
            logging: false
            options:
                replication: true
        monolog:
            type: predis
            alias: monolog
            dsn:
                - %redis.host.master%/%redis.client.logger%?alias=master
                - %redis.host.slave1%/%redis.client.logger%
                - %redis.host.slave2%/%redis.client.logger%
            logging: false
            options:
                replication: true
        cache:
            type: predis
            alias: cache
            dsn:
                - %redis.host.master%/%redis.client.cache%?alias=master
                - %redis.host.slave1%/%redis.client.cache%
                - %redis.host.slave2%/%redis.client.cache%
            logging: false
            options:
                replication: true
        metadata:
            type: predis
            alias: metadata
            dsn:
                - %redis.host.master%/%redis.client.metadata%?alias=master
                - %redis.host.slave1%/%redis.client.metadata%
                - %redis.host.slave2%/%redis.client.metadata%
            logging: %kernel.debug%
            options:
                replication: true
        result:
            type: predis
            alias: result
            dsn:
                - %redis.host.master%/%redis.client.result%?alias=master
                - %redis.host.slave1%/%redis.client.result%
                - %redis.host.slave2%/%redis.client.result%
            logging: %kernel.debug%
            options:
                replication: true
        query:
            type: predis
            alias: query
            dsn:
                - %redis.host.master%/%redis.client.query%?alias=master
                - %redis.host.slave1%/%redis.client.query%
                - %redis.host.slave2%/%redis.client.query%
            logging: %kernel.debug%
            options:
                replication: true
        page:
            type: predis
            alias: page
            dsn:
                - %redis.host.master%/%redis.client.page%?alias=master
                - %redis.host.slave1%/%redis.client.page%
                - %redis.host.slave2%/%redis.client.page%
            logging: false
            options:
                replication: true
        revive:
            type: predis
            alias: revive
            dsn:
                - %redis.host.master%/%redis.client.revive%?alias=master
                - %redis.host.slave1%/%redis.client.revive%
                - %redis.host.slave2%/%redis.client.revive%
            logging: false
            options:
                replication: true
        ga:
            type: predis
            alias: ga
            dsn:
                - %redis.host.master%/%redis.client.ga%?alias=master
                - %redis.host.slave1%/%redis.client.ga%
                - %redis.host.slave2%/%redis.client.ga%
            logging: false
            options:
                replication: true
        default:
            type: predis
            alias: default
            dsn:
                - %redis.host.master%/%redis.client.default%?alias=master
                - %redis.host.slave1%/%redis.client.default%
                - %redis.host.slave2%/%redis.client.default%
            logging: %kernel.debug%
            options:
                replication: true
    session:
        client: session
        prefix: sess
        use_as_default: true
        ttl: 1200
    doctrine:
        metadata_cache:
            client: metadata
            entity_manager: default
            document_manager: default
        result_cache:
            client: result
            entity_manager: default
        query_cache:
            client: query
            entity_manager: default
    monolog:
        client: monolog
        key: monolog
monolog:
    handlers:
        main:
            type: service
            id: snc_redis.monolog.handler
            level: debug
```
but when i'm storing data into client, it stored into one client (the last one). how to replicate data into seperate client?
