### ISSUE TITLE
doctrine result cache can't cache to redis server

### ISSUE THREAD

**Issue by Icefish** [snc/SncRedisBundle#25]
Hello
i wanna using SncRedisBundle to cache doctrine result cache on redis server;

This is my config:
 config.yml:

```
snc_redis:
    connections:
        default:
            alias: default
            host: %redis_host%
            port: %redis_port%
            database: 0
        session:
            alias: session
            host: %redis_host%
            port: %redis_port%
            database: 0
    clients:
        default:
            alias: default
            connection: default
        session:
            alias: session
            connection: session
```

config_dev.yml :

```
snc_redis:
    session:
        client: session
    doctrine:
        result_cache:
            client: default
            entity_manager: default
```

I found result_cache always can not cache on redis server.
But session and query_cache can cache on redis server.

Have i missed some config to config_dev.yml?
