### ISSUE TITLE
Metadata caching fails on PHP7 phpredis

### ISSUE THREAD

**Issue by Hast** [snc/SncRedisBundle#259]
Ubunti 14.04
Symfony 3.0.4
PHP 7.0.6RC

Config:

```
snc_redis:
    clients:
        doctrine_cache:
            type: phpredis
            alias: doctrine_cache
            dsn: '%redis_dsn.doctrine_cache%'
    doctrine:
        metadata_cache:
            client: doctrine_cache
            entity_manager: default
        result_cache:
            client: doctrine_cache
            entity_manager: default
        query_cache:
            client: doctrine_cache
            entity_manager: default
```

Running command:

> sudo -u www-data -H php bin/console doctrine:schema:validate --env=prod

I'm getting an error result:

```
root@server:/var/www/dev# sudo -u www-data -H php bin/console doctrine:schema:validate --env=prod
[Mapping]  FAIL - The entity-class 'AppBundle\Entity\Subscription' mapping is invalid:
* The association AppBundle\Entity\Subscription#order refers to the inverse side field AppBundle\Entity\Order#subscription which does not exist.
* The referenced column name 'id' has to be a primary key column on the target entity class 'AppBundle\Entity\Order'.
* The join columns of the association 'order' have to match to ALL identifier columns of the target entity 'AppBundle\Entity\Order', however '' are missing.
* The referenced column name 'id' has to be a primary key column on the target entity class 'AppBundle\Entity\Room'.
* The join columns of the association 'room' have to match to ALL identifier columns of the target entity 'AppBundle\Entity\Room', however '' are missing.
* The referenced column name 'id' has to be a primary key column on the target entity class 'AppBundle\Entity\Price'.
* The join columns of the association 'subscribedPrice' have to match to ALL identifier columns of the target entity 'AppBundle\Entity\Price', however '' are missing.

  [Doctrine\ORM\ORMException]
  Column name `id` referenced for relation from AppBundle\Entity\Subscription towards AppBundle\Entity\Order does not exist.
```

Which is strange, because everything works with PHP 5.6.*, and the mapping looks valid (I use yml). It also works when I turn off the caching.

Mapping:
```
AppBundle\Entity\Subscription:
    type:  entity
    table: subscription
    repositoryClass: AppBundle\Repository\SubscriptionRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    oneToOne:
        order:
            inversedBy: subscription
            targetEntity: Order

AppBundle\Entity\Order:
    type: entity
    table: orders
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToOne:
        subscription:
            mappedBy: order
            targetEntity: Subscription
```
