### ISSUE TITLE
DSN defination problem: Cluster hostname

### ISSUE THREAD

**Issue by faruktemur** [snc/SncRedisBundle#267]
Hi @snc ,

We successfuly connect to redis when we define hostname of all 3 nodes in redis cluster.

We are also connecting to redis cluster when we define directly AWS LoadBalancer's hostname to DSN. But, client is not catching MOVED exceptions. As we understand client is not connecting as cluster mode if we define only 1 hostname.

my config.yml

```
snc_redis:
    clients:
        cluster:
            type: predis
            alias: cluster
            logging: "%kernel.debug%"
            dsn: ['redis://example.eu-west-1.elb.amazonaws.com']
            options:
                profile: 2.4
                connection_timeout: 10
                connection_persistent: true
                read_write_timeout: 30
                iterable_multibulk: false
                throw_errors: true
                cluster: "redis-cluster"
                replication: false
```
