### ISSUE TITLE
Empty entities loaded from Redis second level cache

### ISSUE THREAD

**Issue by BourotBenjamin** [snc/SncRedisBundle#272]
We configured redis some weeks ago in our test environment and it was working fine.

Now we try to use it in our prod environment, we've got issues.
Sometimes, some of our users are empty and when we try to get informations, it crash our app.

Example : 
When we call : 

> `$user->getLanguage()->getLocale()` 

Symfony screams that getLanguage returns null (But the user have a language and without redis, it works fine)

There is the config : 

```

snc_redis:
    # configure predis as client
    clients:
        doctrine:
            type: predis
            alias: cache_doctrine
            dsn: %cache_server_dsn%
    # configure doctrine caching
    doctrine:
        metadata_cache:
            client: cache_doctrine
            entity_manager: default
            document_manager: default
        result_cache:
            client: cache_doctrine
            entity_manager: default
            document_manager: default
            namespace: "dcrc:"
        query_cache:
            client: cache_doctrine
            entity_manager: default


services:
    snc_second_level_cache:
        class: %snc_redis.doctrine_cache.class%
        calls:
            - ["setRedis", ["@snc_redis.cache_doctrine"]]
            - ["setNamespace", ["DoctrineSecondLevelCache"]] 

doctrine:
    orm:
        entity_managers:
            default:
                metadata_cache_driver: redis
                query_cache_driver: redis
                result_cache_driver: redis
                second_level_cache:
                        region_cache_driver:
                             type: service
                             id: snc_second_level_cache
                        region_lock_lifetime: 60
                        log_enabled: true
                        region_lifetime: 3000
                        enabled: true
                        regions:
                            region_user:
                                lifetime: 3000
                                cache_driver:
                                    type: service
                                    id: snc_second_level_cache
                            region_language:
                                lifetime: 3000
                                cache_driver:
                                    type: service
                                    id: snc_second_level_cache

` 
```

On user : 
`

```

/**
 * User
 *
 * @ORM\Table(name="users")
 * @ORM\Entity(repositoryClass="Acme\UserBundle\Entity\UserRepository")
 * @ORM\HasLifecycleCallbacks
 * @ExclusionPolicy("all")
 * @XmlRoot("User")
 * @ORM\AttributeOverrides({
 *      @ORM\AttributeOverride(name="usernameCanonical", column=@ORM\Column(type="string", name="username_canonical", length=255, unique=true, options={"collation"="utf8_bin"})),
 *      @ORM\AttributeOverride(name="emailCanonical", column=@ORM\Column(type="string", name="email_canonical", length=255, unique=true, options={"collation"="utf8_bin"})),
 * })
 * @ORM\Cache(usage="NONSTRICT_READ_WRITE", region="region_user")
 */

class User extends BaseUser
{


    /**
     * @ORM\ManyToOne(targetEntity="Language")
     * @ORM\JoinColumn(name="actual_lang_id", referencedColumnName="id")
     * @Expose
     * @Groups({"All"})  
     * @ORM\Cache(usage="NONSTRICT_READ_WRITE")
     */
    private $language;
`
```

I don't understand why my entities are empty, and when I clear the redis cache, the page can be loaded again. (And the problem would appear again in a few hours)
