### ISSUE TITLE
How to configure second-level cache

### ISSUE THREAD

**Issue by peter-gribanov** [snc/SncRedisBundle#281]
I install dependencies in composer
```json
"require": {
    "predis/predis": "1.1.*",
    "snc/redis-bundle": "2.0.*",
}
```
configure snc_redis
```yaml
snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: '%redis.default.dns%'
            logging: '%kernel.debug%'
        doctrine:
            type: predis
            alias: doctrine
            dsn: '%redis.doctrine.dns%'
            logging: '%kernel.debug%'

    doctrine:
        metadata_cache:
            client: doctrine
            entity_manager: default
            namespace: 'dmc:'
        result_cache:
            client: doctrine
            entity_manager: default
            namespace: 'drc:'
        query_cache:
            client: doctrine
            entity_manager: default
            namespace: 'dqc:'
        second_level_cache:
            client: doctrine
            entity_manager: default
            namespace: 'dslc:'
```
create second level cache service
```yaml
snc_second_level_cache:
    class: '%snc_redis.doctrine_cache_predis.class%'
    arguments: [ '@snc_redis.doctrine' ]
```
configure doctrine
```yaml
doctrine:
    orm:
        default_entity_manager: default
        entity_managers:
            default:
                auto_mapping: true
                connection: default
                # enable caching
                metadata_cache_driver: redis
                query_cache_driver: redis
                result_cache_driver: redis
                second_level_cache:
                    region_cache_driver:
                        type: service
                        id: snc_second_level_cache
                    enabled: true
                    regions:
                        region_schedule_event:
                            lifetime: 300
                            cache_driver:
                                type: service
                                id: snc_second_level_cache
```
configure entity
```php
/**
 * @ORM\Table(name="schedule_event")
 * @ORM\Entity(repositoryClass="Repository\ScheduleEventRepository")
 * @ORM\Cache(usage="NONSTRICT_READ_WRITE", region="region_schedule_event")
 */
class ScheduleEvent
{
    // ...
}
```
use cache in repository
```php
class ScheduleEventRepository extends EntityRepository
{
    /**
     * @param \DateTime $time
     *
     * @return ScheduleEvent[]
     */
    public function getTodayProgram(\DateTime $time)
    {
        return $this
            ->createQueryBuilder('e')
            ->andWhere('e.status = :event_status')
            ->andWhere('e.date_end_utm > :start')
            ->andWhere('e.date_start_utm < :end')
            ->orderBy('e.date_start_utm', 'ASC')
            ->setParameter(':start', $time->getTimestamp())
            ->setParameter(':end', $time->modify('+1 day')->getTimestamp())
            ->setParameter(':event_status', ScheduleEvent::STATUS_ENABLED)
            ->getQuery()
            ->setCacheable(true)
            ->setLifetime(60)
            ->useResultCache(true, 60)
            ->setCacheRegion('region_schedule_event')
            ->getResult();
    }
}
```
and i catch exception
```
Entity "ScheduleEvent" not configured as part of the second-level cache.
```
what am i doing wrong?
