### ISSUE TITLE
Cluster for failover

### ISSUE THREAD

**Issue by ranpafin** [snc/SncRedisBundle#284]
Hello,

we've adopted elasticache (AWS) as Redis implementation and at the present time we're facing an issue with multiple endpoint.

The failover is handled AWS side by moving away master attribute from the unresponsive node. The master attribute could not be pre-determined as it may change anytime.

consider the following, minimal, configuration:

```
a_client_name:
    alias: a_client_alias
    dsn:
      - endpoint_1
      - endpoint_2
    type: predis
    options:
      cluster: Snc\RedisBundle\Client\Predis\Connection\PredisCluster
      replication: false
```
it raises an exception in the predis client (predis/predis/src/Client.php:162):

```
Warning: call_user_func_array() expects parameter 1 to be a valid callback, no array or string given 
```
by looking at #283 it seems it may be related to the cluster option but changing the cluster option to a string constant does not solve the problem.

I'm not sure if is a miss-configuration issue or something else.

Thanks.
