### ISSUE TITLE
DSN values for Platform.sh host

### ISSUE THREAD

**Issue by treetop1500** [snc/SncRedisBundle#286]
Setting up redis config for a site that's being hosted on platform.sh and we are getting a 502 Bad Gateway response from them when we configure the DSN to the host they provide us.  

From their Redis environment variable, we get the host 'redis.internal' plus we get a port number.  I have tried configuring the SNC bundle using the DSN: 

`redis://redis.internal`
and also 
`redis://redis.internal:XXXX`

(XXXX being the provided port number).  This throws the 502 Bad Gateway Errror at Platform.sh.  Locally I'm using `redis://localhost` and it works perfectly.

If I remove the "redis://" protocol from the DSN and use either:

`redis.internal`
or 
`redis.internal:XXXX`

 The bundle throws an exception due to a malformed DSN.

Thank you in advance.  For reference my SNC config is as follows:  the `redis_host` parameter is either 'redis://localhost` (working) or one of the many combinations I've tried listed above.

```
snc_redis:
    clients:
        default:
            type: phpredis
            alias: default
            dsn: "%redis_host%"
    doctrine:
        metadata_cache:
            client: default
            entity_manager: default          # the name of your entity_manager connection
            document_manager: default        # the name of your document_manager connection
        result_cache:
            client: default
            entity_manager: [default, read]  # you may specify multiple entity_managers
        query_cache:
            client: default
            entity_manager: default
        second_level_cache:
            client: default
            entity_manager: default
```
