### ISSUE TITLE
Document how to use this bundle with the Symfony Cache component.

### ISSUE THREAD

**Issue by Sander-Toonen** [snc/SncRedisBundle#291]
Symfony 3.1 comes with the a cache component. I believe it should be possible to configure the `app` and `system` pools to use SncRedis, however no documentation or examples are available. Could this use case be added to the documentation?

**Comment by teohhanhui** [comment]
Use the `RedisAdapter` directly: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Cache/Adapter/RedisAdapter.php

**Comment by Sander-Toonen** [comment]
I use SNCRedis for spooling mail and in some other places for non-caching purposes (locking and spooling) as well. So it would be nice to reuse the same connection. I managed to do this using the following config:

```
framework:
    cache:
        app: cache.adapter.redis
        default_redis_provider: snc_redis.default
```

Another advantage of this setup is that cache calls using the cache component will be included in the SNCRedis-item in developer toolbar. I thought it might be worth mentioning this possibility in the documentation.

**Comment by reypm** [comment]
@Sander-Toonen is this configuration working? I am working exactly on the same thing and don't have a clue in how to achieve this, could you help with some examples and setup from your experience?

**Comment by teohhanhui** [comment]
@reypm You can refer here: https://github.com/symfony/framework-bundle/blob/fc11aa3f2c0170efd354b4e3badaf1fb6455327b/Tests/Functional/app/CachePools/redis_config.yml

What @Sander-Toonen gave above is correct.

**Comment by reypm** [comment]
@teohhanhui yes but even though the docs [here](https://symfony.com/blog/new-in-symfony-3-1-cache-component) are really poor. At least a working example should be enough can you provide some of them?

**Comment by crashev** [comment]
Anyway it should be a good idea that some kind of mention of Symfony 3 Cache Component was put somewhere here in docs. Right now it's a bit confusing how SncRedisBundle releates to this new Cache Component, how they can work together and if there is even still a need to use SncRedisBundle for new applications if there is new component handling this out of the box.

**Comment by bruno-ds** [comment]
As there are two configurable cache pool `cache.app` and `cache.system`, I wanted to avoid collision by storing them in a separate DB, please find the conf I used: 
```
#app/config/services.yml
    framework_cache_app.redis:
        parent: cache.adapter.redis
        tags:
          - {name: "cache.pool", provider: "snc_redis.framework_cache_app", clearer: "cache.default_clearer"}

    framework_cache_system.redis:
        parent: cache.adapter.redis
        tags:
          - {name: "cache.pool", provider: "snc_redis.framework_cache_system", clearer: "cache.default_clearer"}     
```

```

snc_redis:
    clients:
        # ...
        framework_cache_app:
            type: predis
            alias: framework_cache_app
            dsn: "%redis_dsn.framework_cache_app%"
        framework_cache_system:
            type: predis
            alias: framework_cache_system
            dsn: "%redis_dsn.framework_cache_system%"
```
