### ISSUE TITLE
Is able to divide SwiftMailer's spool into multiple ? (Is able to divide (redis)spool's keyName into multiple ?)

### ISSUE THREAD

**Issue by helloooideeeeea** [snc/SncRedisBundle#295]
Hello.

I want to divide spool's key name into each spool.
Is able to ?

thanks.

following is config.yml.

swiftmailer:

```
mailers:
    spool_mailer:
        transport: "%mailer_transport%"
        host:      "%mailer_host%"
        username:  "%mailer_user%"
        password:  "%mailer_password%"
        port: "%mailer_port%"
        encryption: ~
        spool:
            type: service
            id: snc_redis.swiftmailer.spool
```

snc_redis:

```
clients:
    default:
        type: predis
        alias: default
        dsn: redis://hogehoge.com
        logging: false
swiftmailer:
    client: default
    key: swiftmailer <- I want to divide keys into multiple.
```
