### ISSUE TITLE
Fatal error when installing this bundle.

### ISSUE THREAD

**Issue by ansien12** [snc/SncRedisBundle#299]
```
Attempted to load class "Redis" from the global namespace.
Did you forget a "use" statement?
```

```
 * @author Pierre Boudelle <pierre.boudelle@gmail.com> 
 */ 
class Client extends Redis 
{ 
    /** 
     * @var RedisLogger 
     */ 
```

```
snc_redis:
    clients:
        default:
            type: phpredis
            alias: default
            dsn: redis://localhost
```

predis works, but phpredis gives this error. I'm on the latest version using windows 10, anyone know how to fix?
