### ISSUE TITLE
DDOS possible? Is it safe to store every custom session id passed?

### ISSUE THREAD

**Issue by AlexanderMatveev** [snc/SncRedisBundle#300]
## Config

``` yml
framework:
    ...
    session:
        handler_id: snc_redis.session.handler
    ...
snc_redis:
    clients:
        ...
        session:
            type: predis
            alias: session
            dsn: redis://...
            options:
                prefix: session:
    session:
        client: session
...
```
## Client request

``` text
Cookie: PHPSESSID=CLIENT:CREATED:THIS:SESSION:ID:BY:HIMSELF
Accept-Language: ru
Accept: */*
Accept-Encoding: gzip, deflate
```
## Checking client session saved

``` bash
$ redis-cli
127.0.0.1:6379> AUTH ...
127.0.0.1:6379> keys session:*
1) "session:sessionCLIENT:CREATED:THIS:SESSION:ID:BY:HIMSELF"
```
## Review

So client can generate own session id value and the value will be saved as is.
