### ISSUE TITLE
SncRedis doesn't work with runtime environment variables

### ISSUE THREAD

**Issue by luishdez** [snc/SncRedisBundle#302]
Currently SncRedis doesn't allow to use the new environment variables, apparently this bundle does something before the envs are setted. So you can't use `redis_dsn: "%env(REDIS_DSN)%"` because you receive that literal string instead the current env value.

Info: http://symfony.com/blog/new-in-symfony-3-2-runtime-environment-variables
PR: https://github.com/symfony/symfony/pull/19681

In the PR there is a comment: 

> magnusnordlander commented on 20 Aug
This is an interesting approach, but it is not as backwards compatible as one would think. There are bundles out there today, which as a part of their extension actually manipulate parameters. SncRedisBundle e.g. splits DSNs in the extension. Passing one of these parameters there will at best cause some kind of syntax error in the bundle, or at worst cause old environment values to be cached.

**Comment by robinvdvleuten** [comment]
What needs to be done to get this functionality in the bundle? It's a must have for using this bundle running on any PAAS provider, see https://github.com/symfony/symfony/issues/20850

**Comment by hmazter** [comment]
I think I have this working by having a parameter: `redis_host: '%env(REDIS_HOST)%'`
and in the config use: `dsn: "redis://%redis_host%/1"`
and for the environment variable: `REDIS_HOST=192.168.50.1`

**Comment by dkreuer** [comment]
I'm hitting this issue too. @hmazter could you provide a working example with symfony 3.2 please?

**Comment by hmazter** [comment]
@dkreuer Here is an extract of my files.

parameters.yml:
```
parameters:
    redis_host: '%env(REDIS_HOST)%'
    env(REDIS_HOST): localhost
```

and config.yml:
```
snc_redis:
    clients:
        cache:
            type: predis
            alias: cache
            dsn: "redis://%redis_host%/1"
```

**Comment by dkreuer** [comment]
@hmazter This configuration is working because you are neither defining the redis port as environment variable nor the redis database index.

If you would have used the following configuration it would not have worked:
```
parameters:
    redis_host: "%env(REDIS_HOST)%"
    redis_port: "%env(REDIS_PORT)%"
    redis_db: "%env(REDIS_DBIDX)%"
    env(REDIS_HOST): "localhost"
    env(REDIS_PORT): 6379
    env(REDIS_DBIDX): 0

snc_redis:
    clients:
        cache:
            type: predis
            alias: cache
            dsn: "redis://%redis_host%:%redis_port%/%redis_db%"
```

This might be due to strict regex checking but yet not alone.

**Comment by hmazter** [comment]
I'm no expert at all, but my understanding is that when using `%%` parameters in config files they are just replaced, and not up to the Bundle/package to handle that.
But I will check if my case works with port database

**Comment by dkreuer** [comment]
From my understanding the dsn is splitted into separate variables for host, port and database in the CompilerPass and these parts are validated against regular expressions. The parameters are not replaced in the compiler pass because the compiled container will be cached. Runtime environment variables would not be of use in this case because the compiled value will already be static.

One could argue that there are two possibilities to fix this issue:
1) Do not validate strictly in the compiler pass but validate in the latest possible moment right before connecting to redis, which might lead to runtime issues which otherwise could not be caught before.
2) Do not split the dsn in the compiler pass but in the latest possible moment right before connecting to redis, which might lead to runtime issues which otherwise could not be caught before.

Imho the second is a bit cleaner because all validation and splitting happens in one place as before.

**Comment by hmazter** [comment]
Seems you are correct and I was just lucky that I only needed to use the host as a environment variable since it worked with that.

**Comment by snc** [comment]
Please try this with latest master.

**Comment by dkreuer** [comment]
Looks good to me. Thank you very much for fixing this.

**Comment by robinvdvleuten** [comment]
@snc it's still an issue on provider like Heroku where you're given an environment variable containing the complete dns as described [here](https://devcenter.heroku.com/articles/heroku-redis#connecting-in-php) and my corresponding merged PR for Symfony [here](https://github.com/symfony/symfony/pull/20891)

**Comment by leopro** [comment]
@snc are you planning to create a tag? say 2.0.2 ?

**Comment by snc** [comment]
Yeah, but before I would like to support Heroku etc., I just don't know a good solution yet.

**Comment by oleg-andreyev** [comment]
This works fine for single host, but when set of nodes/cluster it's still an issue.

**Comment by teohhanhui** [comment]
@snc I believe this method should work? https://github.com/symfony/symfony/blob/v3.3.0/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/CachePoolPass.php#L108-L110

**Comment by teohhanhui** [comment]
For Predis, we don't need to do our own DSN parsing, just call `Parameters::parse` https://github.com/nrk/predis/blob/v1.1.1/src/Connection/Parameters.php#L66-L129 (after resolving the parameters, of course).

**Comment by snc** [comment]
Anyone using Heroku that could have a look at #353 ?

**Comment by elmariachi111** [comment]
So, I can confirm that this is working with a (simple) heroku setup using heroku redis. Tested it with a local redis and with a live heroku application and they both connect (no repl, no cluster) successfully and work as expected. Code looks a little... bloated? but that primarily seems to be due to iKlaus' mentioned bc effort.

**Comment by Restless-ET** [comment]
Hi there.

I'm not being able to get this working. Using SF 3.3.6 and the latest master of this bundle.

Here's my setup:
```
parameters:
    redis_host: "%env(REDIS_HOST)%"
    redis_port: "%env(REDIS_PORT)%"
    redis_db: "%env(REDIS_DBIDX)%"
    env(REDIS_HOST): "redis_service"
    env(REDIS_PORT): 6379
    env(REDIS_DBIDX): 0

# Redis Configuration for session storage
snc_redis:
    clients:
        session:
            type: predis
            alias: session
            dsn: "redis://%redis_host%:%redis_port%/%redis_db%"
            logging: false
    session:
        locking: false
        client: session
        prefix: sess_
```

Locally everything works fine. But in staging I have the `REDIS_HOST` env var set with a different value, but this is not assuming it and keeps using `"redis_service"`.

I've even been poking around the bundle code for the last few hours trying to find the problem and get this working but with no luck.

Any help/pointers to solve this are greatly appreciated.

Thanks in advance.

PS - I doubt this is related but just in case I'm leaving the note... I'm running my symfony app inside a docker container and redis on another.
