### ISSUE TITLE
Redis endpoints should be parameters

### ISSUE THREAD

**Issue by james-bw** [snc/SncRedisBundle#310]
As noted in http://symfony.com/doc/current/best_practices/configuration.html, best practice is to "Define the infrastructure-related configuration options in the app/config/parameters.yml file."

As is common in enterprise environments, I have different environments with different external redis servers/clusters. The common stuff that is in config.yml makes sense, but the endpoints do not, as these are infrastructure-specific. 

This is a request to change the server and cluster dsn definition to be moved to parameters.yml, and related documentation updated. I have tried to do this manually before without success.

**Comment by ivoba** [comment]
you can already put your dsn in parameters.yml

```
snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: "%redis.dsn%"
```

**Comment by james-bw** [comment]
Can you provide a full example of how this should be configured in parameters, specifically with cluster? Something like this?

```
parameters:
    redis
        session_cluster.dsn:
                - redis://host1/0?alias=master
                - redis://host2/0
                - redis://host3/0
                - redis://host4/0
        cache_cluster.dsn:
                - redis://host1/1?alias=master
                - redis://host2/1
                - redis://host3/1
                - redis://host4/1
```

and then the config can be:

```
snc_redis:
    clients:
        cluster:
            type: predis
            alias: session_cluster
            dsn: "%redis.session_cluster.dsn%"
        cluster:
            type: predis
            alias: cache_cluster
            dsn: "%redis.cache_cluster.dsn%"
    session:
        client: session_cluster
```

Will that work?
