### ISSUE TITLE
second_level_cache is always saved in DB0

### ISSUE THREAD

**Issue by gadelkareem** [snc/SncRedisBundle#313]
```
doctrine:
    dbal:
        driver:   pdo_mysql
    orm:
        metadata_cache_driver: redis
        result_cache_driver: redis
        query_cache_driver: redis
        second_level_cache:
            region_cache_driver: redis
            enabled: true
            log_enabled: true
            regions:
                user_region:
                    lifetime: 86400
                    cache_driver: redis

snc_redis:
    clients:
        session:
            type: phpredis
            alias: session
            dsn: redis://localhost/0
            logging: "%kernel.debug%"
        metadata_cache:
            type: phpredis
            alias: metadata_query_cache
            dsn: redis://localhost/1
            logging: "%kernel.debug%"
        result_cache:
            type: phpredis
            alias: result_cache
            dsn: redis://localhost/2
            logging: "%kernel.debug%"
        second_level_cache:
            type: phpredis
            alias: second_level_cache
            dsn: redis://localhost/3
            logging: "%kernel.debug%"
    session:
        client: session
    doctrine:
        metadata_cache:
            client: metadata_query_cache
            entity_manager: default
            document_manager: default
        query_cache:
            client: metadata_query_cache
            entity_manager: default
        result_cache:
            client: result_cache
            entity_manager: default
        second_level_cache:
            client: second_level_cache
            entity_manager: default

```

All client are being saved to their respective DSN except second_level_cache which is always saved to `redis://localhost/0`. Also I am able to see the logging on the profiler while totally disabling SncRedisBundle config does not stop Doctrine caching to redis.

**Comment by gadelkareem** [comment]
Looks like the only solution is to create a service still:

```
#app/services.yml
    app.second_level_cache:
        class: Doctrine\Common\Cache\RedisCache
        calls:
            - ["setRedis", ["@snc_redis.second_level_cache"]]
            - ["setNamespace", ["DoctrineSecondLevelCache"]]

#app/config.yml
doctrine:
    dbal:
        driver:   pdo_mysql
    orm:
        metadata_cache_driver: redis
        result_cache_driver: redis
        query_cache_driver: redis
        second_level_cache:
            region_cache_driver:
                type: service
                id: app.second_level_cache
            enabled: true
            log_enabled: "%kernel.debug%"
            regions:
                user_region:
                    lifetime: 86400
                    cache_driver:
                        type: service
                        id: app.second_level_cache

```
