### ISSUE TITLE
second_level_cache (redis)namespace does not work

### ISSUE THREAD

**Issue by MyDigitalLife** [snc/SncRedisBundle#320]
I have defined a namespace for my second level cache for doctrine. However this namespace is not used. Looking into this it looks like doctrine sets its own namespace that Redis uses. Is this a bug or something that cannot be changed because of how doctrine does this? If its not possible to set the namespace for the second level cache i think it would be a good idea to make sure this configuration option fails. 

My yml file looks like this:
```
doctrine:
    orm:
        second_level_cache:
            region_cache_driver:
                type: redis
            region_lifetime: 100

snc_redis:
    doctrine:
        second_level_cache:
            client: doctrine_cache
            entity_manager: default
            namespace: "slc_%release_version%"
```
