### ISSUE TITLE
How to inject @snc_redis to own service ?

### ISSUE THREAD

**Issue by marcin-iwanicki** [snc/SncRedisBundle#367]
Hi, I try to inject '@snc_redis' to my own service in Symfony 3.3 but i get error on type hint.
What Instance i must use in __constructor method on my service ?

**Comment by charleslxh** [comment]
\Predis\Client

**Comment by fvozar** [comment]
@charleslxh: I tried your suggestion, but I got this error: 

```
Cannot autowire service "MyService": argument "$redis" of method "__construct()" references class "Predis\Client" but no such service exists. It cannot be auto-registered because it is from a different root namespace. 
```

I'm using Symfony 4, SncRedisBundle is registered. Did someone get same error?

**Comment by orderbynull** [comment]
Got same error about autowiring

**Comment by curry684** [comment]
We can look into this for 3.0 as we're targetting Symfony 3.4+ there and thus we have extra options for autowiring.

**Comment by curry684** [comment]
Given current limitations around dual phpredis/predis support there's not much we can do to make this any more convenient than the suggested aliasing suggested above by @Majkl578. It's also in line with Symfony's current best practices to leave the decision with the end-user how to alias his dependencies into autowiring.

So if you want autowiring, alias the typehinted class to the correct client you want to inject.

**Comment by nacholibre** [comment]
@curry684 @Majkl578 @marcin-iwanicki 

Given the current symfony state, in symfony 3.4/4.4 you can do this:
```YAML
// snc_redis.yaml or config.yaml
snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: "%env(REDIS_URL)%"

        reverse_ns:
            type: predis
            alias: redis_second
            dsn: "%env(REDIS_SECOND_URL)%"
```


```YAML
//services.yaml
Predis\Client: '@snc_redis.default'
Predis\Client $redisSecond: '@snc_redis.redis_second'
```

And then you can inject like this:
```PHP
<?php
//....
class SomeClass
{
  public function __construct(\Predis\Client $redis)
  {
    //$redis is '@snc_redis.default'
  }
}
```

```PHP
<?php
//....
class SomeOtherClass
{
  public function __construct(\Predis\Client $redisSecond)
  {
    //$redis is '@snc_redis.redis_second'
  }
}
```

You can read more about it here https://symfony.com/doc/4.4/service_container/autowiring.html#dealing-with-multiple-implementations-of-the-same-type
