### ISSUE TITLE
Default/Test configuration

### ISSUE THREAD

**Issue by leek** [snc/SncRedisBundle#37]
After the recent upgrade, configuration merges do not happen like they used to. I have a default `config.yml` like this:

``` yaml
snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: %redis.default.dsn%
            logging: %kernel.debug%
```

And what used to be an override in `config_test.yml` like this:

``` yaml
snc_redis:
    clients:
        default:
            dsn: %redis.test.dsn%
```

However, this converts my `dsn` override into an array of `dsns`, rather than obeying that I want the `dsn` overwritten.
