### ISSUE TITLE
ERR unknown command 'SET' when I use sentinel mode?

### ISSUE THREAD

**Issue by charleslxh** [snc/SncRedisBundle#371]
I got an error: `ERR unknown command 'SET'` when I use sentinel mode, the following is my configration:

`config.yml`:

```yaml
snc_redis:
    clients:
        cache:
            type: predis
            alias: cache
            dsn: "%redis.dsn%"
            options:
                replication: "%redis.replication%"
                service: "%redis.service%"
                profile: "%redis.version%"
                connection_timeout: 10
                read_write_timeout: 30
                parameters:
                    database: "%redis.database%"
                    password: "%redis.password%"
```

paramters.yml:

```yaml
# Redis
  redis.dsn:
    - redis://redis_sentinel:26379
  redis.replication: sentinel
  redis.service: mymaster
  redis.password: 123456
  redis.database: 10
  redis.version: 3.0
```

some information:

- symfony version: 3.2
- predis version: 1.1.1
- snc redis bundle version: ^2.0

When I request myu server, I got an error `unknown command 'SET'`, but when I connect redis master directly, it does work, not any errors.

I want to know why, and how can I config sentinel?
