### ISSUE TITLE
BUG: session_wirte_close() error!

### ISSUE THREAD

**Issue by charleslxh** [snc/SncRedisBundle#377]
environment:

```yml
symfony: 3.3
snc_redis_bundle: 2.0.4
php: 7.0.26
```

session config in `config.yml`

```yml
freamwork:
    session:
        storage_id: session.storage.native
        handler_id: session.proxy.handler
        name: "%session.name%"
        cookie_lifetime: 0
        cookie_path: /
        cookie_domain: "%session.domain%"
        cookie_secure: true
        cookie_httponly: true
        gc_divisor: ~
        gc_probability: ~
        gc_maxlifetime: ~
        save_path: "%kernel.cache_dir%/sessions"
        metadata_update_threshold: 0
```

`session.proxy.handler` is my session proxy, but is use `snc_redis.session.handler` to save session.

```yml
session.proxy.handler:
    public: false
    class: SiteBundle\Session\ReadOnlySessionProxy
    arguments: ["@snc_redis.session.handler", "@security.token_storage"]
```

I got this error:

```bash
User Warning: session_write_close(): Failed to write session data with Snc\RedisBundle\Session\Storage\Handler\RedisSessionHandler handler
```

when I remove `handler_id: session.proxy.handler`, it works normally with no error.
