### ISSUE TITLE
Single \Predis\Connection\Parameters instance should be wrapped in array when using sentinel replication.

### ISSUE THREAD

**Issue by dzolnierz** [snc/SncRedisBundle#381]
Config below results in  `ERR unknown command 'SET'` when trying to set session data. Parsed DSN is passed as an instance of `\Predis\Connection\Parameters` to `\Predis\Client` which results in sending SET/GET to Redis Sentinel instead of real Redis node.

```
snc_redis:
    clients:
        session:
            type: predis
            alias: session
            dsn:
                - redis://redis-sentinel:26379                 
            options:
                replication: sentinel
                service: master
```

**Comment by dzolnierz** [comment]
This issue is related to: https://github.com/nrk/predis/issues/476

**Comment by petitphp** [comment]
Hello @dzolnierz 

I just ran into the same issue. Did you find a solution/workaround ?

**Comment by adammwood** [comment]
Our temporary workaround to this issue is to just duplicate the declaration, causing it to be correctly converted to an array.

```yaml
snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn:
                # These are duplicated as a workaround to: https://github.com/snc/SncRedisBundle/issues/381
                - redis://redis-sentinel:26379
                - redis://redis-sentinel:26379
```
