### ISSUE TITLE
How to define a database name in snc_redis configuration

### ISSUE THREAD

**Issue by Oppodelldog** [snc/SncRedisBundle#387]
Hi, I have got a problem with defining a custom database name in snc_redis configuration.
Somehow dns is used only as host and port is appended automatically.

Runtime configuration
PHP7.1
Symfony: 2.8

**composer - depencencies**
```json
    "snc/redis-bundle": "2.0.0",
    "predis/predis": "1.1.1",
```

**Here's my configuration:**
```yml
parameters:
  app.redis_address: 'redis://redis/myDB'

snc_redis:
  clients:
    default:
      type: predis
      alias: default
      logging: true
      dsn: "redis://%app.redis_address%"
```

**The following error is returned. As you can see somehow the port is not inserted properly.**
```php
php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution [tcp://redis/myDB:6379]
```

I also tried to define the dns with port included to help the configuration somwhow, but that also failed.
```yaml
app.redis_address: 'redis:6379/myDB'
```
This fails during parameter creation.

```
 The redis DSN "redis:\/\/redis:6379\/myDB" is invalid.
```
