### ISSUE TITLE
Defining profile by env variable fails

### ISSUE THREAD

**Issue by Majkl578** [snc/SncRedisBundle#391]
With config like:
```yaml
parameters:
    env(REDIS_PROFILE): 3.2

snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: '%env(REDIS_DSN)%'
            options:
                profile: '%env(REDIS_PROFILE)%'
                throw_errors: true

```

The env variable for _profile_ fails to resolve:

```
Symfony\Component\DependencyInjection\Exception\EnvParameterException: Incompatible use of dynamic environment variables "REDIS_PROFILE" found in parameters.

vendor/symfony/dependency-injection/Compiler/Compiler.php:112
vendor/symfony/dependency-injection/ContainerBuilder.php:711
vendor/symfony/http-kernel/Kernel.php:513
vendor/symfony/http-kernel/Kernel.php:125
vendor/symfony/framework-bundle/Test/KernelTestCase.php:61
tests/Functional/KernelTestCase.php:16

Caused by
Predis\ClientException: Unknown server profile: '%env(REDIS_PROFILE)%'.

vendor/predis/predis/src/Profile/Factory.php:94
vendor/snc/redis-bundle/DependencyInjection/SncRedisExtension.php:187
vendor/snc/redis-bundle/DependencyInjection/SncRedisExtension.php:123
vendor/snc/redis-bundle/DependencyInjection/SncRedisExtension.php:51
vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php:71
vendor/symfony/http-kernel/DependencyInjection/MergeExtensionConfigurationPass.php:39
vendor/symfony/dependency-injection/Compiler/Compiler.php:95
vendor/symfony/dependency-injection/ContainerBuilder.php:711
vendor/symfony/http-kernel/Kernel.php:513
vendor/symfony/http-kernel/Kernel.php:125
vendor/symfony/framework-bundle/Test/KernelTestCase.php:61
tests/Functional/KernelTestCase.php:16
```

Tested with dev-master as well.
