### ISSUE TITLE
AWS Elasticache Redis Cluster : Uncaught PHP Exception Predis\Response\ServerException: MOVED

### ISSUE THREAD

**Issue by ebarault** [snc/SncRedisBundle#402]
Hi, 

AWS provides a single configuration endpoint for an Elasticache Redis Cluster (x shards, y replicas per shards).

With the following configuration, i get this error: 
```
Uncaught PHP Exception Predis\Response\ServerException: "MOVED 2777 w.x.y.z:6379" at /var/www/html/vendor/predis/predis/src/Client.php line 370
```

```
snc_redis:
    clients:
       default:
         type: predis
         alias: default
         dsn:
           - my-redis.cmfj2h.ng.0001.euw3.cache.amazonaws.com:6379
         options:
           profile: 3.2
           cluster: redis
           replication: false
```

I use snc_redis bundle **2.0.4** and predis bundle **1.1.1**

I find very little doc (mostly in issues) about server-side replication/sharding support option (`cluster: redis`).

Has anyone solved this?
