### ISSUE TITLE
[Bug] No commands in profiler using symfony cache with predis

### ISSUE THREAD

**Issue by vchebotarev** [snc/SncRedisBundle#407]
Hello.
SncRedisBundle profiler doesn't display command when i'm using symfony cache with snc redis "predis" client only. Going deeper - commands are not even catched.

With "phpredis" everything is fine.

So this is my yml (yes it also possible configuring "framework -> cache -> pools" but in this case it doesn't matter )
```yml
services:
    app.cache.psr6:
        class: Symfony\Component\Cache\Adapter\RedisAdapter
        arguments:
            - '@snc_redis.default'

    app.cache.psr16:
        class: Symfony\Component\Cache\Simple\RedisCache
        arguments:
            - '@snc_redis.default'

snc_redis:
    clients:
        default:
            type:    predis
            alias:   default
            dsn:     'redis://localhost'
            logging: '%kernel.debug%'
```
This is example of usage in controller
```php
        $cachePool = $this->get('app.cache.psr6');
        $cachePoolItem = $cachePool->getItem('app.cache.psr6');
        $cachePoolItem->set('app.cache.psr6');
        $cachePool->save($cachePoolItem);

        $cachePsr16 = $this->get('app.cache.psr16'); //also uses RedisTrait
        $cachePsr16->set('app.cache.psr16', 'app.cache.psr16');

        $sncClient = $this->get('snc_redis.default');
        $sncClient->set('snc_redis.default', 'snc_redis.default');
```

But the profiler looks like this
![e032e7dea3](https://user-images.githubusercontent.com/2445241/38422274-cd094536-39b2-11e8-81c8-6395adb8d721.png)

**Values present in redis. I CHEKED !**

When i try to change client type to "phpredis" everything goes fine
```yml
snc_redis:
    clients:
        default:
            type:    phpredis
            alias:   default
            dsn:     'redis://localhost'
            logging: '%kernel.debug%'
```
![a974b75e04](https://user-images.githubusercontent.com/2445241/38422422-66ca9724-39b3-11e8-9f88-6441c8973516.png)

My application where i demonstrated it is: 
blank symfony 3.4.7
predis/predis v1.1.1
snc/redis-bundle 2.0.6
