### ISSUE TITLE
[Bug] DSN is not interpolated at runtime with environment variable

### ISSUE THREAD

**Issue by B-Galati** [snc/SncRedisBundle#410]
Hello,

I just upgraded from 2.0.6 to 2.1.0 and my app broke because the DSN was not updated.

It looks like the issue is similar to https://github.com/snc/SncRedisBundle/issues/302.

I checked my cache and the value of the config is hard-coded instead of using the env variable.

Here is my config :

```
snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: "%env(REDIS_DSN)%"
    session:
        client: default
        prefix: session
```

Am I missing something ?

In the meantime I moved back to 2.0.6 and everything is back to normal.

Let me know for anything and thanks for your help.
