### ISSUE TITLE
Support for runtime Environment Variables

### ISSUE THREAD

**Issue by mykiwi** [snc/SncRedisBundle#421]
Since Symfony [3.2](https://symfony.com/blog/new-in-symfony-3-2-runtime-environment-variables) we can use environment variables. But it's not supported by the bundle (yet).

Example:

- my config:
```
snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: "%env(REDIS_URL)%"
```
- code generated in the cache:
```php
return $this->services['snc_redis.default'] = new \Predis\Client(
    new \Predis\Connection\Parameters(
        array(
            'scheme' => 'tcp',
            'host' => 'localhost',
            'port' => 6379,
            'password' => NULL,
            // ...
```

Because it use the default value `REDIS_URL=redis://localhost` instead of building the object at runtime with the env variable.

Here is how [SwiftMailerBundle](https://github.com/symfony/swiftmailer-bundle/blob/master/DependencyInjection/SwiftmailerExtension.php#L75) deal with it.
