### ISSUE TITLE
Support pre-building the Symfony container without the Redis server available (or known)

### ISSUE THREAD

**Issue by dkarlovi** [snc/SncRedisBundle#434]
In containerized apps, it's common to pre-warm cache while building the image. This allows for the container to come in with warm cache and just start working as if it's here forever.

With SncRedisBundle, this is currently not possible as it seems the bundle is trying to connect to the Redis server at build time. But, not only the Redis server might not be available at build time, its connection string is also not known (supplied later via env).

```yaml
parameters:
    env(REDIS_URL): ""

snc_redis:
    clients:
        default:
            type: phpredis
            alias: default
            dsn: "%env(REDIS_URL)%"
        cache:
            type: phpredis
            alias: cache
            dsn: "%env(REDIS_URL)%"
        session:
            type: phpredis
            alias: session
            dsn: "%env(REDIS_URL)%"
    session:
        client: session

framework:
    session:
        handler_id: snc_redis.session.handler
    cache:
        app: cache.adapter.redis
        default_redis_provider: snc_redis.cache
```

This config doesn't allow the container to be built. First the extension claims the URL is invalid:
https://github.com/snc/SncRedisBundle/blob/38de7edaeacaa1c8ce5aa5fa1eba7697c6c051d9/DependencyInjection/SncRedisExtension.php#L110
