### ISSUE TITLE
Creating multiple session keys when using snc_redis.session.handler

### ISSUE THREAD

**Issue by SvetlinStaev** [snc/SncRedisBundle#438]
I am using SncRedisBundle with **Symfony 3.4.11** and **Redis 4.0.9** using the following configuration:

```
framework:
    session:
        handler_id: "snc_redis.session.handler"
        cookie_lifetime: 86400
        cookie_domain: "%cookie_domain%"
        cookie_httponly: false
```

and

```
snc_redis:
    clients:
        session:
            type:     "phpredis"
            alias:    "session"
            dsn:      "redis://%redis_hostname%:%redis_port%"
            logging:  false
    session:
        client: "session"
        locking: false
        prefix: "PHPREDIS_SESSION:"
        ttl: 86400
```

I was using the default PHP session handler connected to the Redis instance and it is working fine but I wanted to try the session handler that the bundle provided. When I switch to it using the configuration above it is working but it is generating one additional key per request. If I visit 10 pages on the site I get 11 session keys - one with corresponding to the id of the cookie `PHPREDIS_SESSION` and 10 more with different ids. The additional ones are returning empty string, while the one with the id property returns the serialized session data. The pages have AJAX request an endpoint of the same domain. When I turn off the request, there are less keys generated, which leads me to believe it might be reinitiating the session on each AJAX request.

My question is whether these additional keys are intentionally there or are caused by some bug. I am running it locally, if I run it on production with x number of users visiting y number of pages these empty keys could exponentially build up.
