### ISSUE TITLE
command redis:flushall The client default is not defined

### ISSUE THREAD

**Issue by lcp0578** [snc/SncRedisBundle#441]
config.yml

```
snc_redis:
    clients:
        default:
            type: phpredis
            alias: default
            dsn: "redis://lcp0578@localhost:6379"
            #dsn: "redis://localhost:6379"
            logging: "%kernel.debug%"
        cache:
            type: phpredis
            alias: cache
            dsn: redis://lcp0578@localhost:6379
            #dsn: redis://localhost:6379
            options:
                profile: 2.2
                connection_timeout: 10
                read_write_timeout: 30
        session:
            type: phpredis
            alias: session
            dsn: redis://lcp0578@localhost:6379
            #dsn: redis://localhost:6379
```
output:

```
chunpengs-MacBook-Pro:adjust lcp0578$ php7 bin/console redis:flushall
The client default is not defined
chunpengs-MacBook-Pro:adjust lcp0578$ php7 bin/console redis:flushall --client=cache
The client cache is not defined
chunpengs-MacBook-Pro:adjust lcp0578$
```

test in controller

```
class DefaultController extends Controller
{
    public function indexAction()
    {
        $redisService = $this->get('snc_redis.default');
        dump($redisService);
        $cacheService = $this->get('snc_redis.cache');
        dump($cacheService);
    }
}
```
dump output:
```
DefaultController.php on line 13:
Redis {#2588 ▼
  isConnected: true
  host: "localhost"
  port: 6379
  auth: "lcp0578"
  dbNum: 0
  timeout: 5.0
  persistentId: null
  options: {▼
    READ_TIMEOUT: 0.0
    SERIALIZER: NONE
    PREFIX: null
    SCAN: NORETRY
  }
}
DefaultController.php on line 15:
Redis {#779 ▼
  isConnected: true
  host: "localhost"
  port: 6379
  auth: "lcp0578"
  dbNum: 0
  timeout: 10.0
  persistentId: null
  options: {▼
    READ_TIMEOUT: 0.0
    SERIALIZER: PHP
    PREFIX: null
    SCAN: NORETRY
  }
}
```

symfony v3.4.11
