### ISSUE TITLE
No master server available for replication after upgrade to 2.1.6

### ISSUE THREAD

**Issue by markitosgv** [snc/SncRedisBundle#449]
Hi,

I'm getting this error "No master server available for replication" when I upgraded from 2.1.3 to 2.1.6, but the issue was introduced in 2.1.4 release.

My snc_redis configuration is:

```yaml
snc_redis:
    clients:
        front:
            type: predis
            alias: front
            dsn:
                - "%env(REDIS_MASTER_URL)%?alias=master"
                - "%env(REDIS_SLAVE_URL)%"
            logging: "%kernel.debug%"
            options:
                replication: true
```
