### ISSUE TITLE
permit to set the ttl for each clients

### ISSUE THREAD

**Issue by bruno-ds** [snc/SncRedisBundle#456]
Hello,

I'd like to be able to define the TTL per client.
This would leverage the possibility to use more easily the `volatile-lru` to have some client being evicted and other not evicted, on a client basis.

## why?
I think this is necessary to me because being hosted on AWS and using elasticache, I'm billed per server.
Each server can only have one LRU policy.
So I'd like to use `volatile-lru` in order to have an LRU policiy, but only for the clients of my choose.

**Comment by curry684** [comment]
What would we have to do for this? I'm not familiar with Elasticache myself, but `volatile-lru` is a server setting, not a client setting. So if you can configure it in AWS, we're compatible with it as long as you set the right TTLs.

**Comment by bruno-ds** [comment]
has it is asked here : https://github.com/snc/SncRedisBundle/issues/84
I'd like to have the ability to provide a TTL for each clients, ie: 
```
snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: redis://localhost
            ttl: 3600
```

if I'm not wrong, it is possible only for sessions, not directly on the redis client but on another conf. node.

**Comment by LaurynasGerbutavicius** [comment]
+1

**Comment by curry684** [comment]
A "client" is nothing more than a wrapper around a single Redis connection. It cannot have a TTL since it does not set anything in Redis - you the developer do the actual calls to `set($key, $value, $ttl)` and we cannot default them.

What you appear to be asking is something entirely different - an extension to the session handlers to take and apply a TTL to the things they store in their clients. Recommended practice for that is simply to store data like this in a separate Redis client, with `allkeys-lru` as the eviction policy. Which actually makes sense for everything 'cached' as well by definition, as it also allows you infinitely more control about the resources used by the evictionable and production data.

The only reason the obvious solution to the problem doesn't work for you is that you're, summarizing indignantly, not willing to shell out extra AWS costs to do it right   😉   I don't think that really makes it any priority to be handled or fixed right now.

**Comment by curry684** [comment]
Actually it seems we already support it: https://github.com/snc/SncRedisBundle/blob/2.1/Session/Storage/Handler/RedisSessionHandler.php#L219, it was merged in https://github.com/snc/SncRedisBundle/pull/73.

The docs are at https://github.com/snc/SncRedisBundle/blob/master/Resources/doc/index.md#user-content-sessions

**Comment by bruno-ds** [comment]
For the merge #73: yes I've read the code, but as I said it only handle the session : https://github.com/snc/SncRedisBundle/pull/73/commits/edd0587e552f22d87c538c939f5aad0bae686970#diff-fd809ec659d77076dce28d9ea225b8f6

For your point about my issue not being relevant, I can only agree with you : I don't want to pay an extra server and I'm lazy so I'd like to have a magical method. I think I'll code it myself. Thank you for your time :)

**Comment by curry684** [comment]
Well the point is that the session is just about the only place we can enforce it - like I said on the client level the Redis API simply does not allow us to enforce it as the TTL is set on a per-call level, and we don't interfere with the actual calls to Redis itself.

**Comment by B-Galati** [comment]
@bruno-ds If you want you can have a similar feature by using Symfony cache pools => https://symfony.com/doc/current/reference/configuration/framework.html#default-lifetime
Which can use any phpredis/predis service.

As an example:

```yaml
framework:
     cache:
        app: cache.adapter.redis
        default_redis_provider: snc_redis.cache
    cache:
        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
                default_lifetime: 25200 # 1 week
```
