### ISSUE TITLE
profiler_storage not working with Symfony 4

### ISSUE THREAD

**Issue by Teaxtor** [snc/SncRedisBundle#461]
Hey all,

today I tried using the profiling storage feature from the snc redis bundle like this:
```yaml
snc_redis:
    clients:
        profiler:
            type: phpredis
            alias: profiler
            dsn: redis://%redis_host_profiler%/3
            logging: false
    profiler_storage:
        client: profiler
        ttl: 86400
```
But somehow still the FileProfilerStorage from Symfony got used when I debugged. After explicitly overwriting the service, it works:
```yaml
snc_redis:
    clients:
        profiler:
            type: phpredis
            alias: profiler
            dsn: redis://%redis_host_profiler%/3
            logging: false

services:
    profiler.storage:
        class: Snc\RedisBundle\Profiler\Storage\RedisProfilerStorage
        arguments:
            - '@snc_redis.profiler'
            - 86400
```

Is it possible, that the latest changes in Symfony 4 broke the overwriting mechanism you used, or did I miss anything? :S

I'm using Symfony 4.1.2 with Snc/Redis 2.1.4

Best,

Sebastian

**Comment by rpkamp** [comment]
Not sure why that won't work for you. It works fine for me on Symfony 4.1.6 with snc/redis 2.1.7

Maybe try updating to those versions, or hard deleting the cache (`rm -rf /paht/to/your/symfony/project/var/cache`) and try again?

**Comment by curry684** [comment]
Just tried to reproduce this in Symfony 4.2.3 with 3.0.0-RC2. Added following file to `config/packages/dev/snc_redis.yaml`:
```
snc_redis:
    clients:
        profile:
            type: phpredis
            alias: profiler
            dsn: redis://redis/5
    profiler_storage:
        client: profiler
        ttl: 86400
```
On first 5 it started gathering profiles in Redis instead of file and everything was still ok.

Therefore closing this bug.
