### ISSUE TITLE
Request getSession() cause an UndefinedMethodException

### ISSUE THREAD

**Issue by blitzen12** [snc/SncRedisBundle#485]
Calling the getSession() method from request object cause an UndefinedMethodException
Attempted to call an undefined method named "setLogger" of class "Predis\Connection\StreamConnection".

```
public getUserInfoAction(Request $request){
     $session = $request->getSession();
}
```
config.yml
```
snc_redis:
    clients:
        session:
          type: predis
          alias: session
          dsn: redis://password@localhost:6379
    session:
        client: session
        prefix: nexlife_
framework:
    session:
        handler_id: snc_redis.session.handler
```
