### ISSUE TITLE
Connection to redis is mandatory with 2.1.8?

### ISSUE THREAD

**Issue by fredleger** [snc/SncRedisBundle#497]
It seems that the connection to redis is mandatory with the v2.8.x branch at least. 

Running a simple `php app/console cache:clear -n --no-warmup ` ends up with an error: 

```
 [Predis\Connection\ConnectionException]    
  Connection refused [tcp://localhost:6379]
```

config:
```
snc_redis:
    # configure predis as client
    clients:
        default:
            type: predis
            alias: default
            dsn: redis://localhost
            options:
                read_write_timeout: -1
```

Any way to workaround that behavior ?
