### ISSUE TITLE
Redis connection (in Doctrine cache) gets initialized on each command

### ISSUE THREAD

**Issue by theravel** [snc/SncRedisBundle#510]
I have a Symfony 4.1 app, where I use Doctrine and want to setup Redis cache for Doctrine.

Here is a part of composer.json

```
"snc/redis-bundle": "^2.1",
"symfony/doctrine-bridge": "^4.1",
"symfony/proxy-manager-bridge": "^4.1",
```
Here is yml config file:

```
snc_redis:
    clients:
        doctrine_cache:
            type: phpredis
            alias: doctrine_cache
            dsn: '%my_dsn%'
    doctrine:
        metadata_cache:
            client: doctrine_cache
            entity_manager: default
```
The problem is: on the very first time when Symfony tries to generate cache for all DI containers, it initializes Redis connection. This means for example when I run any console command, it tries to connect to redis. Example:
```
// very first command after git clone and composer install
php bin/console about
```

Output:
```
In PhpredisClientFactory.php line 64:
php_network_getaddresses: getaddrinfo failed: No such host is known.
```
I expect that Redis cache service will be initialized lazily, otherwise I cannot run other build commands on independent (non having Redis) environment. Can someone advise please?
