### ISSUE TITLE
How to use the database parameter

### ISSUE THREAD

**Issue by peter-gribanov** [snc/SncRedisBundle#513]
```yml
snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: '%redis_dsn%'
            logging: '%kernel.debug%'
            options:
                parameters:
                    database: 1
```
