### ISSUE TITLE
Can't use env variable for type configuration

### ISSUE THREAD

**Issue by alexander-schranz** [snc/SncRedisBundle#518]
e.g.:

```env
REDIS_ADAPTER=predis
```

```yaml
snc_redis:
    clients:
        session:
            type: '%env(REDIS_ADAPTER)%'
            # ...
```

> In BaseNode.php line 422: Invalid configuration for path "snc_redis.clients.session.type": The redis client type "" is invalid.

Seems like env variables can't be validated in the Configuration.php and thats why the error seems to happen?
