### ISSUE TITLE
Predis Client constructed without logger

### ISSUE THREAD

**Issue by MichaelKubovic** [snc/SncRedisBundle#519]
Hello, I'm fighting a container-related issue. Under certain circumstances, with Predis default client, logging enabled, the client is passed an `Options` instance that references `ConnectionFactory`, that is not properly built before it's used from the `Client`'s constructor.

The result is, that in the runtime, `ConnectionFactory` has `wrapper` property set to null.

My setup results into following method in the compiled dev container.
```php
/**
 * Gets the public 'snc_redis.default' shared service.
 *
 * @return \Predis\Client
 */
protected function getSncRedis_DefaultService()
{
    $a = new \Predis\Profile\RedisVersion320();
    $b = new \Snc\RedisBundle\Client\Predis\Connection\ConnectionFactory($a);

    $this->services['snc_redis.default'] = $instance = new \Predis\Client(..bla bla, not important...,  'connections' => $b]));

    $b->setConnectionWrapperClass('Snc\\RedisBundle\\Client\\Predis\\Connection\\ConnectionWrapper');
    $b->setLogger(($this->privates['snc_redis.logger'] ?? $this->getSncRedis_LoggerService()));

    return $instance;
}
```

My guess was that the bundle should have declared factory for Options, so that symfony knows that the setter is called on a factory, but that didn't work as the factory class ended up inlined instead.

Any ideas how to make the container call the setters before passing the reference to `Options`?

**Comment by B-Galati** [comment]
Hello @MichaelKubovic ,

Could you tell us what you are trying to achieve? I am not sure to understand what is the issue.

Basically you would like to have one ConnectionFactory service per client?

**Comment by MichaelKubovic** [comment]
That's the way container extension defines ConnectionFactory services. It declares one ConnectionFactory service per client alias with id defined as `sprintf('snc_redis.%s_connectionfactory', $clientAlias);`.

That's not the problem. The problem is, that setter methods on the ConnectionFactory are called too late. Constructor of `\Predis\Client` relies on ConnectionWrapper and Logger instances being set, but they are set after the client constructor gets called in the container.

**Comment by MichaelKubovic** [comment]
Just to be clear, the code example above is generated code that causes the issue. I'm trying to figure out what possible could lead to it.

**Comment by B-Galati** [comment]
Thanks It's clearer.

Not able to reproduce it, could you provide:

- the output of `composer show` so that I can see the symfony version and redis bundle you are using
- the full bundle config used
- the output of `bin/console debug:config snc_redis`

As an alternative you could set up a reproducer.

**Comment by MichaelKubovic** [comment]
composer show | grep symfony
```
Restricting packages listed in "symfony/symfony" to "4.2.*"
friendsofsymfony/rest-bundle              2.5.0               This Bundle provides various tools to rapidly develop RESTful API's with Symfony
sentry/sentry-symfony                     2.3.0               Symfony integration for Sentry (http://getsentry.com)
symfony/asset                             v4.2.9              Symfony Asset Component
symfony/browser-kit                       v4.2.9              Symfony BrowserKit Component
symfony/cache                             v4.2.9              Symfony Cache component with PSR-6, PSR-16, and tags
symfony/config                            v4.2.9              Symfony Config Component
symfony/console                           v4.2.9              Symfony Console Component
symfony/contracts                         v1.1.5              A set of abstractions extracted out of the Symfony components
symfony/css-selector                      v4.2.9              Symfony CssSelector Component
symfony/debug                             v4.2.9              Symfony Debug Component
symfony/dependency-injection              v4.2.9              Symfony DependencyInjection Component
symfony/doctrine-bridge                   v4.2.9              Symfony Doctrine Bridge
symfony/dom-crawler                       v4.2.9              Symfony DomCrawler Component
symfony/dotenv                            v4.2.9              Registers environment variables from a .env file
symfony/event-dispatcher                  v4.2.9              Symfony EventDispatcher Component
symfony/expression-language               v4.2.9              Symfony ExpressionLanguage Component
symfony/filesystem                        v4.2.9              Symfony Filesystem Component
symfony/finder                            v4.2.9              Symfony Finder Component
symfony/flex                              v1.2.7              Composer plugin for Symfony
symfony/form                              v4.2.9              Symfony Form Component
symfony/framework-bundle                  v4.2.9              Symfony FrameworkBundle
symfony/http-foundation                   v4.2.9              Symfony HttpFoundation Component
symfony/http-kernel                       v4.2.9              Symfony HttpKernel Component
symfony/inflector                         v4.2.9              Symfony Inflector Component
symfony/intl                              v4.2.9              A PHP replacement layer for the C intl extension that includes additional data from the ICU library.
symfony/maker-bundle                      v1.11.6             Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writing boilerplate code.
symfony/monolog-bridge                    v4.2.9              Symfony Monolog Bridge
symfony/monolog-bundle                    v3.4.0              Symfony MonologBundle
symfony/options-resolver                  v4.2.9              Symfony OptionsResolver Component
symfony/orm-pack                          v1.0.6              A pack for the Doctrine ORM
symfony/phpunit-bridge                    dev-master d3ccbc9  Symfony PHPUnit Bridge
symfony/polyfill-intl-icu                 v1.11.0             Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring                 v1.11.0             Symfony polyfill for the Mbstring extension
symfony/polyfill-php72                    v1.11.0             Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/process                           v4.2.9              Symfony Process Component
symfony/profiler-pack                     v1.0.4              A pack for the Symfony web profiler
symfony/property-access                   v4.2.9              Symfony PropertyAccess Component
symfony/proxy-manager-bridge              v4.2.9              Symfony ProxyManager Bridge
symfony/psr-http-message-bridge           v1.2.0              PSR HTTP message bridge
symfony/routing                           v4.2.9              Symfony Routing Component
symfony/security                          v4.2.9              Symfony Security Component
symfony/security-bundle                   v4.2.9              Symfony SecurityBundle
symfony/serializer                        v4.2.9              Symfony Serializer Component
symfony/stopwatch                         v4.2.9              Symfony Stopwatch Component
symfony/templating                        v4.2.9              Symfony Templating Component
symfony/translation                       v4.2.9              Symfony Translation Component
symfony/twig-bridge                       v4.2.9              Symfony Twig Bridge
symfony/twig-bundle                       v4.2.9              Symfony TwigBundle
symfony/validator                         v4.2.9              Symfony Validator Component
symfony/var-dumper                        v4.2.9              Symfony mechanism for exploring and dumping PHP variables
symfony/var-exporter                      v4.2.9              A blend of var_export() + serialize() to turn any serializable data structure to plain PHP code
symfony/web-profiler-bundle               v4.2.9              Symfony WebProfilerBundle
symfony/webpack-encore-bundle             v1.6.0              Integration with your Symfony app & Webpack Encore!
symfony/yaml                              v4.2.9              Symfony Yaml Component
```

composer show | grep redis
```
Restricting packages listed in "symfony/symfony" to "4.2.*"
predis/predis                             v1.1.1              Flexible and feature-complete Redis client for PHP and HHVM
snc/redis-bundle                          2.1.9               A Redis bundle for Symfony
```

cat config/packages/snc_redis.yaml
```yaml
parameters:
    env(REDIS_DSN): ''

snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: '%env(REDIS_DSN)%'
    session:
        client: default
        ttl: '%app.session.timeout%'
```

bin/console debug:config snc_redis
```
Current configuration for extension with alias "snc_redis"
==========================================================

snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsns:
                - '%env(REDIS_DSN)%'
            logging: true
            options:
                connection_async: false
                connection_persistent: false
                connection_timeout: 5
                read_write_timeout: null
                iterable_multibulk: false
                throw_errors: true
                serialization: default
                profile: default
                cluster: null
                prefix: null
                service: null
    session:
        client: default
        ttl: 3600
        prefix: session
        locking: true
        spin_lock_wait: 150000
    class:
        client: Predis\Client
        client_options: Predis\Configuration\Options
        connection_parameters: Predis\Connection\Parameters
        connection_factory: Snc\RedisBundle\Client\Predis\Connection\ConnectionFactory
        connection_wrapper: Snc\RedisBundle\Client\Predis\Connection\ConnectionWrapper
        phpredis_client: Redis
        phpredis_connection_wrapper: Snc\RedisBundle\Client\Phpredis\Client
        logger: Snc\RedisBundle\Logger\RedisLogger
        data_collector: Snc\RedisBundle\DataCollector\RedisDataCollector
        doctrine_cache_phpredis: Doctrine\Common\Cache\RedisCache
        doctrine_cache_predis: Doctrine\Common\Cache\PredisCache
        monolog_handler: Monolog\Handler\RedisHandler
        swiftmailer_spool: Snc\RedisBundle\SwiftMailer\RedisSpool
```
