### ISSUE TITLE
Service "snc_redis.phpredis.monolog" still is used in Monolog When set client type is "phpredis"

### ISSUE THREAD

**Issue by phakpoom** [snc/SncRedisBundle#530]
When i upgrade 2 -> 3 i ran into this error.
Error
```
  !!  In CheckExceptionOnInvalidReferenceBehaviorPass.php line 86:                                                                                                                                                                        
  !!                                                                                                                                                                                                                                      
  !!    The service "snc_redis.monolog.handler" has a dependency on a non-existent                                                                                                                                                        
  !!    service "snc_redis.phpredis.monolog".      
```

My config
```yaml
snc_redis:
    clients:
        monolog:
            type: phpredis
            alias: monolog
            logging: false
            dsns:
            - "%redis_monolog_dns%"
    monolog:
        client: monolog
        key: monolog
```
Because this line
https://github.com/snc/SncRedisBundle/blob/caf5cd4497e86c683c47b20c50bd5079d719a50d/DependencyInjection/SncRedisExtension.php#L391

temporary fix
```yaml
services:
    'snc_redis.phpredis.monolog': '@snc_redis.monolog'
```
