### ISSUE TITLE
Warning: Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by methodeprog** [snc/SncRedisBundle#536]
I try to install 
composer require snc/redis-bundle 3.0.0 or 3.0.1 or dev-master / 3.x-dev
I got this issue.
After this issue when i try php bin/console i got the same issue till i run composer remove snc/redis-bundle.
Finally i could not install snc/redis-bundle
///////////////////////////////
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!
!!  In Configuration.php line 98:
!!
!!    Warning: Invalid argument supplied for foreach()
!!
!!
!!
Script @auto-scripts was called via post-update-cmd

Installation failed, reverting ./composer.json to its original content.
//////////////
Using Symfony 4.3.4
///////

Please help !

**Comment by alfamegaxq** [comment]
Hello @methodeprog ,

Recently I stumbled on the same issue.

The problem is, that when you install snc/redis-bundle it creates a configuration file at `config/packages/snc_redis.yaml`, which by default is without any configured client and therefore invalid. try configuring your client details here, clear cache and it should work. config should look something like this:

```
snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: "%env(REDIS_URL)%"
```
