### ISSUE TITLE
Clarification on Cluster Support

### ISSUE THREAD

**Issue by firrae** [snc/SncRedisBundle#541]
Hi there,

I'm working on an older Symfony 2.X application using 2.X of this package and am trying to get cluster support to work and I'm just curious if native Redis Cluster support is only available in the 3.X version of this package? Currently I have: 

```
snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn:
                - redis://127.0.0.1:7000
                - redis://127.0.0.1:7001
                - redis://127.0.0.1:7002
            options:
                cluster: redis
                replication: false
```
But it doesn't seem to connect properly (due to our dev environment I'm not getting any direct errors, but that it can't find keys as expected so it's handling it in it's intended manner). Any clarification on cluster support in version 2.X is appreciated.
