### ISSUE TITLE
Configure doctrine metadata cache with multiple entity manager

### ISSUE THREAD

**Issue by Zlyy** [snc/SncRedisBundle#555]
Hi, after upgrading SncRedisBundle from 2.1.9 to 3.2.1 I have got some metadata cache issues. I'm using Symfony 4.4.

In my app I'm using two entity managers. Here's my current config, created by my ex-coworker:

```
snc_redis:
  clients:
    default:
      type: predis
      alias: default
      dsn: "%env(REDIS_URL)%/1"
      logging: '%kernel.debug%'
  
    doctrine:
      type: predis
      alias: doctrine
      dsn: "%env(REDIS_URL)%/2"
      logging: '%kernel.debug%'

    session:
      type: predis
      alias: session
      dsn: "%env(REDIS_URL)%/3"
      logging: '%kernel.debug%'

    profiler_storage:
      type: predis
      alias: profiler_storage
      dsn: "%env(REDIS_URL)%/4"
      logging: '%kernel.debug%'

  session:
    client: session
    prefix: tp_
    ttl: 28800

  doctrine:
    metadata_cache:
      client: doctrine
      entity_manager: [default, secondOne]
      document_manager: [default, secondOne]
      namespace: 'dmc:'
    result_cache:
      client: doctrine
      entity_manager: [default, secondOne]
      document_manager: [default, secondOne]
      namespace: 'drc:'
    query_cache:
      client: doctrine
      entity_manager: [default, secondOne]
      document_manager: [default, secondOne]
      namespace: 'dqc:'
    second_level_cache:
      client: doctrine
      entity_manager: [default, secondOne]
      document_manager: [default, secondOne]
      namespace: 'dslc:'

  profiler_storage:
    client: profiler_storage
    ttl: 600

```

On 2.x there's no errors at all. But after update, metedata cache is mixed up. After debugging doctrine is getting metadata for entity form other entity manager. After removing second one from here:

```
  doctrine:
    metadata_cache:
      client: doctrine
      entity_manager: [default]
      document_manager: [default, secondOne]
      namespace: 'dmc:'

```

Everything seems to be OK. Is that configuration error SncRediBundle bug?

**Comment by B-Galati** [comment]
Hi, 

I don't really know but my recommendation is to completely remove everything under `snc_reds.doctrine` key and directly use doctrine bundle to configure doctrine. Something like this should do the job:

```yaml
doctrine:
  orm:
    auto_generate_proxy_classes: false
    metadata_cache_driver:
      type: pool
      pool: doctrine.system_cache_pool
    query_cache_driver:
      type: pool
      pool: doctrine.system_cache_pool
    result_cache_driver:
      type: pool
      pool: doctrine.result_cache_pool

framework:
  cache:
    pools:
      doctrine.result_cache_pool:
        adapter: cache.app
        default_lifetime: 25200 # 1 week
      doctrine.system_cache_pool:
        adapter: cache.system
```

Note that you should not use redis to store metadata cache, it's counter productive as metadata cache result from a static analysis of the codebase.
