### ISSUE TITLE
BC break: zAdd does not support adding multiple members at once

### ISSUE THREAD

**Issue by umpirsky** [snc/SncRedisBundle#559]
We notices this after upgrading `snc/redis-bundle (2.1.4 => 3.2.1)`.

In `2.1.4`:

```
$this->get('snc_redis.mydb')->zAdd('key', 1, 'item1', 2, 'item2');
```

Adds both members.

In `3.2.1`, same code only adds the first member.

**Comment by curry684** [comment]
This is by definition not a BC break as it's a major version upgrade.

Also, `zAdd` is not our API but part of phpRedis. They may have inadvertently broken this behavior in their own latest upgrade as they were required to revise all parameters.

According to https://github.com/phpredis/phpredis#zadd it should work, if it doesn't in the latest phpRedis version you should file an issue there.

**Comment by umpirsky** [comment]
I didn't upgrade phpRedis, I only updated this `snc/redis-bundle` from `2.1.4` to `3.2.1`.

In `2.1.4` this worked, in `3.2.1` it does not work. How can this be phpRedis issue?

**Comment by curry684** [comment]
`$this->get('snc_redis.mydb')` returns an instance of `\Redis`, provided by phpRedis. This bundle only provides the integrates of phpRedis and Predis in a nice Symfony bundle. The call to `zAdd` and its parameters are on their end.

**Comment by curry684** [comment]
Actually you may be using [Predis](https://packagist.org/packages/predis/predis) instead of phpRedis (this bundle can do both) but since Predis is unmaintained since 2016 you're advised to upgrade to phpRedis in that case.

**Comment by B-Galati** [comment]
Could you show your config @umpirsky ?

**Comment by umpirsky** [comment]
I use phpredis:

```yaml
snc_redis:
    clients:
        mydb:
            alias: mydb
            type: phpredis
            logging: false
            dsn: "redis:///var/run/db0.sock"
            options:
                profile: 4.2
                prefix: "myprefix:"
                read_write_timeout: 10
```
