### ISSUE TITLE
Does not work with API Platform, Docker Builds

### ISSUE THREAD

**Issue by cnizzardini** [snc/SncRedisBundle#560]
With snc/redis-bundle (3.2.1), using the default docker setup provided by Symfony API Platform the error below is encountered on `docker-compose build`:

> Script cache:clear returned with error code 1
> !!  PHP Warning:  Redis::connect(): php_network_getaddresses: getaddrinfo failed: Name does not resolve in /srv/api/vendor/snc/redis-bundle/Factory/PhpredisClientFactory.php on line 155
> !!  
> !!  In PhpredisClientFactory.php line 155:
> !!                                                                         
> !!    php_network_getaddresses: getaddrinfo failed: Name does not resolve  
> !!                                                                         
> !!  
> !!  
> Script @auto-scripts was called via post-install-cmd

If I remove the auto scripts from `composer.json` it works. 

```
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
```

**Comment by B-Galati** [comment]
>using the default docker setup provided by Symfony API Platform

Can you specify what you are talking about exactly please.

Also: 

- What's your config?
- How to reproduce it?

**Comment by cnizzardini** [comment]
Install api platform https://github.com/api-platform/api-platform

snc_redis.yaml:

```
snc_redis:
    clients:
        default:
            type: phpredis
            alias: default
            dsn: "%env(REDIS_URL)%"
            logging: '%kernel.debug%'
    doctrine:
        metadata_cache:
            client: default
            document_manager: default        # the name of your document_manager connection
        result_cache:
            client: default
            document_manager: [default, read]  # you may specify multiple entity_managers
        query_cache:
            client: default
            document_manager: default
        second_level_cache:
            client: default
            document_manager: default
```
