### ISSUE TITLE
"snc_redis.session.handler" has a dependency on a non-existent      service "snc_redis.session"

### ISSUE THREAD

**Issue by ahmed-bhs** [snc/SncRedisBundle#569]
I'm facing this issue:

In CheckExceptionOnInvalidReferenceBehaviorPass.php line 86:
                                                                               
  The service "snc_redis.session.handler" has a dependency on a non-existent   
  service "snc_redis.session".                                                 

This mys conf:

```
snc_redis:
    session:
        client: session
    clients:
        session:
            type: phpredis
            alias: default
            dsn: "redis://redis:6379"

```
```

framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        enabled: true
        handler_id: snc_redis.session.handler
        cookie_secure: auto
        cookie_samesite: lax

```

Versions:
Symfony version                  4.4.7
snc/redis-bundle                             3.2.1   A Redis bundle for Symfony

any help would be appreciated !
