### ISSUE TITLE
php_network_getaddresses: getaddrinfo failed: Name or service not known

### ISSUE THREAD

**Issue by ahmed-bhs** [snc/SncRedisBundle#570]
Is it possible to disable the Redis connect on test environment ? I'm getting this exception after runing my gitlab ci : php_network_getaddresses: getaddrinfo failed: Name or service not know

**Comment by B-Galati** [comment]
What's your config? Bundle version? Symfony version?

**Comment by curry684** [comment]
You should not change your environment during tests as it makes the process pointless.

You can run Redis instances in [Gitlab CI](https://docs.gitlab.com/ee/ci/services/redis.html), [Travis](https://docs.travis-ci.com/user/database-setup/#redis) or just about any other CI service out there.

**Comment by ahmed-bhs** [comment]
Hey @B-Galati thank you for replying: 
```

snc/redis-bundle                             3.2.1
symfony version                             4.4.7
```

My current test config:
```
snc_redis:
    clients:
        session:
            type: phpredis
            alias: session
            dsn: "%env(REDIS_URL)%"
            logging: "%kernel.debug%"
    session:
        client: "session"


framework:
    test: true
    session:
        storage_id: session.storage.mock_file
        handler_id: session.handler.native_file

```

@curry684 so ther's no way to skip redis connection even, I'm using another session cache handler ? /
