### ISSUE TITLE
How to inject @snc_redis in my controller ?

### ISSUE THREAD

**Issue by ththugues44** [snc/SncRedisBundle#576]
Good morning all

I want to know how to inject the snc_redis.default service into my controller. Impossible I encounter the error "Service" snc_redis.default "not found: even though it exists in the app's container, the container inside" App \ Controller \ Demo \ DemoController "

I use Symfony 4.2, snc_redis 3.2, php 7.4, rediser server 6.0.0

Thank you

**Comment by B-Galati** [comment]
Hello, 

That's because the service is private I guess.

How are you trying to fetch it?

**Comment by ththugues44** [comment]
Hello @B-Galati 

after several attempts, I resolved to create a service:
Extract Services.yaml : 
```
apps.redis_client:
        public : true
        autowire: true
        class: App\Services\RedisClient
        arguments: ['@snc_redis.default']`

Redis: '@snc_redis.default'
```

Extract config snc_redis.yaml : 
```
snc_redis:
    clients:
        default:
            type: phpredis
            alias: default
            dsn: "%env(REDIS_URL)%"
```

Extract Class  App\Services\RedisClient : 

```
namespace App\Services;
use Redis ;

class RedisClient
{
    public function __construct(Redis $sncRedisDefault)
    {
        $this->client    = $sncRedisDefault;
    }
    
    public function clientRedis(){
            return $this->client;
    }
}
```

Extract file my controller : 

```
namespace App\Controller\Demo;
use App\MessengerBus\Tchat\TchatMessage;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\Services\RedisClient;

class DemoController extends AbstractController
{

    /**
     * @Route("/demo/demo", name="demo_demo")
     * @param RedisClient $demo
     */
    public function index(RedisClient $demo)
    {
        var_dump( $demo->clientRedis()->isConnected());
    }
}
```

This is what works for me, but how do I configure if I ever have multiple redis clients?

**Comment by B-Galati** [comment]
There are many ways to configure dependency injection with Symfony. Read this doc https://symfony.com/doc/current/service_container.html if you want to know them ;-)

>This is what works for me, but how do I configure if I ever have multiple redis clients?

Here is one solution (that could be provided by the bundle just like Symfony http client)

```yaml
snc_redis:
  clients:
    default:
      [...your_config..]
    auth:
      [...your_config..]

services:
  _defaults:
    bind:
      Redis $redisDefault: '@snc_redis.default'
      Redis $redisAuth: '@snc_redis.auth'
```
