### ISSUE TITLE
TTL for doctrine cache

### ISSUE THREAD

**Issue by demianchuk** [snc/SncRedisBundle#590]
Hi

I already found some similar issue https://github.com/snc/SncRedisBundle/issues/389

But I am not agree to the end with solution. As for me some ttl option at configuration should be present as without that memory 
resources are not used effectively. There is no sense to keep in memory things that are not necessary any more

It it problematic to add such option to doctrine?

**Comment by B-Galati** [comment]
Hi,

You can have something like this:

```
doctrine:
  orm:
    auto_generate_proxy_classes: false
    metadata_cache_driver:
      type: pool
      pool: doctrine.system_cache_pool
    query_cache_driver:
      type: pool
      pool: doctrine.system_cache_pool
    result_cache_driver:
      type: pool
      pool: doctrine.result_cache_pool

framework:
  cache:
    pools:
      doctrine.result_cache_pool:
        adapter: cache.app
        default_lifetime: 25200 # 1 week
      doctrine.system_cache_pool:
        adapter: cache.system
```

Is it what you wanted to do?
