### ISSUE TITLE
Understand doctrine's configuration

### ISSUE THREAD

**Issue by thomas-hiron** [snc/SncRedisBundle#591]
I added doctrine's second level cache in my project, but I got a concern on the configuration below:

```
snc_redis:
    ...
    doctrine:
        second_level_cache:
            client: cache
            entity_manager: default
```

What does it do exactly?  
It is working perfectly without it, but I don't know if I can safely omit it!

Thanks
