### ISSUE TITLE
AUTH initial command missing when options:parameters:password is specified

### ISSUE THREAD

**Issue by zexa** [snc/SncRedisBundle#592]
Hi, 

It seems like the following settings do not add an `AUTH` initial command

```
snc_redis:
  clients:
    default:
      dsn: "redis://127.0.0.1:8999"
      options:
        parameters:
          password: "passwordInParameters"
```

But these do.

```
snc_redis:
  clients:
    default:
      dsn: "redis://passwordInDSN@127.0.0.1:8999"
```

The expected behavior was that both of these settings styles would do the exact same thing. 

Is the style in the first example deprecated? If not what can I do to make it work?
