### ISSUE TITLE
[Question] Clear redis sessions for a specific client

### ISSUE THREAD

**Issue by ahmed-bhs** [snc/SncRedisBundle#603]
Hello, I have tow separate symfony apps, where each one use the same remote redis cluster defined under `"%redis_url%"` parameter. I'm using in both apps snc/redis-bundle:3.2.2`  for session management.
The problem that when I call `bin/console redis:flushall --client app1_session -n` from the first app =>  all the sessions are deleted from redis it includes sessions related to the second app (client : app2_session).

This is my app 1 config:
```yaml
snc_redis:
    clients:
        app1_session:
            type: phpredis
            alias: app1_session
            dsn: "%redis_url%"
    session:
        client: app1_session
        prefix: "PHPREDIS_SESSION_"
        ttl: 1200
framework:
    session:
        enabled: true
        handler_id: snc_redis.session.handler
```

This is my app 2 config:

```yaml
snc_redis:
    clients:
        app2_session:
            type: phpredis
            alias: app2_session
            dsn: "%redis_url%"
    session:
        client: app2_session
        prefix: "PHPREDIS_SESSION_"
        ttl: 1200
framework:
    session:
        enabled: true
        handler_id: snc_redis.session.handler
```

Any help would be appreciated!
