### ISSUE TITLE
 The service alias "doctrine.orm.default_metadata_cache" does not exist.

### ISSUE THREAD

**Issue by sdonmt** [snc/SncRedisBundle#613]
Using Symfony 4.4 with DoctrineBundle 2.4.2, Doctrine 2.9.0 with this config:
```
snc_redis:
  clients:
    default:
      type: predis
      alias: default
      dsn: '%redis_dsn%'
      logging: false # '%kernel.debug%'
      options:
        connection_timeout: 0
    redses:
      type: predis
      alias: redses
      dsn: '%redis_session_dsn%'
      logging: false # '%kernel.debug%'
      options:
        connection_timeout: 0
    reddoc:
      type: predis
      alias: reddoc
      dsn: '%redis_doctrine_dsn%'
      logging: false # '%kernel.debug%'
      options:
        connection_timeout: 0
  session:
    client: redses
    prefix: '%redis_session_prefix%'
    locking: false
  doctrine:
    metadata_cache: # https://github.com/symfony/symfony/issues/6095
      client: reddoc
      namespace: "%kernel.root_dir%"   # http://stackoverflow.com/questions/28050200/clear-doctrine-cache-in-redis-on-deploy
      entity_manager: default          # the name of your entity_manager connection
      document_manager: default        # the name of your document_manager connection
    result_cache:
      client: reddoc
      entity_manager: [default, read]  # you may specify multiple entity_managers
    query_cache:
      client: reddoc
      entity_manager: default
```

I get  The service alias "doctrine.orm.default_metadata_cache" does not exist on any console command I run and the app is not even able to write cache at all.
<img width="557" alt="Bildschirmfoto 2021-07-01 um 14 07 11" src="https://user-images.githubusercontent.com/85745725/124121829-a89fb600-da75-11eb-905c-fe9b77572aaa.png">

When I comment the doctrine section in the config I seem to get it working but obviously that kills caching :)
Could you help me by any chance or confim the bug at least?
