### ISSUE TITLE
Facing an issue while configure Phpredis Client with symfony

### ISSUE THREAD

**Issue by muhammadnabeelmehmood** [snc/SncRedisBundle#621]
snc_redis.yaml

```
snc_redis:
    class:
        phpredis_client:
            'Snc\RedisBundle\Client\Phpredis\Client'
    clients:
        default:
            type: phpredis
            alias: default
            dsn: redis://127.0.0.1:6379 # (*)
            logging: '%kernel.debug%'
            options:
                replication: sentinel
                service: mymaster
                parameters:
                    database: 1
                    password:
```

services.yaml

```
services:
    Snc\RedisBundle\Client\Phpredis\Client: '@snc_redis.default'
```
    
 RedisController.php

`use Snc\RedisBundle\Client\Phpredis\Client;`
 

```
/** @var  Client */
    private $redisClient;

    public function __construct(Client $client)
    {
        $this->redisClient = $client;
    }
```

```
/**
     * @Route("/keys", name="keys")
     */
    public function indexAction()
    {
        $redisKeys = $this->redisClient->keys('*');
        return $this->json(['keys' => $redisKeys]);
    }
```

**Getting an error** 
`Warning: Class 'Container97esFst\\Client_541ffe9' not found`

Please let me know what am I doing wrong?
