### ISSUE TITLE
Weird order of client service construction inside Symfony compiled PHP

### ISSUE THREAD

**Issue by Pazns** [snc/SncRedisBundle#625]
I'm meeting an issue very much like this one : #519 

With a trivial configuration with two Predis clients, a "cache" client and a "session" client (latter also used for the PHP session support),
I'm getting two different results for each client Symfony service, as follows : 

config
```yml
snc_redis:
    clients:
        session:
            type: predis
            alias: session
            dsn: '%redis_session_dsn%'
            logging: '%kernel.debug%'
            options: '%redis_session_options%'
        cache:
            type: predis
            alias: cache
            dsn: '%redis_cache_dsn%'
            logging: '%kernel.debug%'
            options: '%redis_cache_options%'
    session:
        client: session
        prefix: session

```

var/cache compiled php : 
```php
/**
     * Gets the private 'snc_redis.cache' shared service.
     *
     * @return \Predis\Client
     */
    protected function getSncRedis_CacheService()
    {
        $a = new \Predis\Profile\RedisVersion320();
        $b = new \Snc\RedisBundle\Client\Predis\Connection\ConnectionFactory($a);

        $this->privates['snc_redis.cache'] = $instance = new \Predis\Client(\Snc\RedisBundle\Factory\PredisParametersFactory::create(['read_write_timeout' => NULL, 'iterable_multibulk' => false, 'serialization' => 'default', 'profile' => 'default', 'prefix' => NULL, 'service' => NULL, 'async_connect' => false, 'timeout' => 5, 'persistent' => false, 'exceptions' => true, 'logging' => true, 'alias' => 'cache'], 'Predis\\Connection\\Parameters', 'redis://redis'), new \Predis\Configuration\Options(['read_write_timeout' => NULL, 'iterable_multibulk' => false, 'serialization' => 'default', 'profile' => $a, 'prefix' => NULL, 'service' => NULL, 'async_connect' => false, 'timeout' => 5, 'persistent' => false, 'exceptions' => true, 'connections' => $b]));

        $b->setConnectionWrapperClass('Snc\\RedisBundle\\Client\\Predis\\Connection\\ConnectionWrapper');
        $b->setLogger(($this->privates['snc_redis.logger'] ?? $this->getSncRedis_LoggerService()));

        return $instance;
    }
```
```php
/**
     * Gets the private 'snc_redis.session' shared service.
     *
     * @return \Predis\Client
     */
    protected function getSncRedis_SessionService()
    {
        $a = new \Predis\Profile\RedisVersion320();
        $b = new \Snc\RedisBundle\Client\Predis\Connection\ConnectionFactory($a);
        $b->setConnectionWrapperClass('Snc\\RedisBundle\\Client\\Predis\\Connection\\ConnectionWrapper');
        $b->setLogger(($this->privates['snc_redis.logger'] ?? $this->getSncRedis_LoggerService()));

        return $this->privates['snc_redis.session'] = new \Predis\Client(\Snc\RedisBundle\Factory\PredisParametersFactory::create(['read_write_timeout' => NULL, 'iterable_multibulk' => false, 'serialization' => 'default', 'profile' => 'default', 'prefix' => NULL, 'service' => NULL, 'async_connect' => false, 'timeout' => 5, 'persistent' => false, 'exceptions' => true, 'logging' => true, 'alias' => 'session'], 'Predis\\Connection\\Parameters', 'redis://redis'), new \Predis\Configuration\Options(['read_write_timeout' => NULL, 'iterable_multibulk' => false, 'serialization' => 'default', 'profile' => $a, 'prefix' => NULL, 'service' => NULL, 'async_connect' => false, 'timeout' => 5, 'persistent' => false, 'exceptions' => true, 'connections' => $b]));
    }
```
Notice how in the case of the "cache" instance, the wrapper and logger are setup *after* the construction.
It seems to lead to a null wrapper variable in the Predis ConnectionFactory class, at https://github.com/snc/SncRedisBundle/blob/3.4.0/Client/Predis/Connection/ConnectionFactory.php#L65 more precisely.

I don't understand yet why both services are constructed differently.
I'm currently looking into Symfony code to find why it thought instantiation should be done this way, but it's gonna take a while...

I'm thinking Symfony may be confused by SncRedisBundle about the dependencies of those services, maybe related to some specific order of declarations in services.yml files .
Probably why #519 op got trouble reproducing the bug.

**Comment by Pazns** [comment]
Still investigating.

It seems the order changes once I wire `@snc_redis.cache` service into my project redis cache wrapper.

**Comment by Pazns** [comment]
Sorry I missed the notification somehow.

I ended up finding the issue, that is most certainly a bug in the Symfony DependencyInjection container caused by mis-use of service configuration.
Here is a simplified copy of my exact service config : 
Given `class StorageManager implements CacheableInterface`.
```yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        CacheableInterface:
            calls:
                - [setCache, ['@PredisCache']]

    PredisCache:
        arguments: ['@snc_redis.cache']

    StorageManager:
        calls:
            - [setCache, ['@PredisCache']]
```
Notice how the injection by setter call is defined *twice*.

This works in Symfony 3.4 without issue.
However, in Symfony 4.4 (I worked with 4.4.27 to be exact) it causes the weird inversion of service configuration of SncRedisBundle as stated above.

Really weird.
