### ISSUE TITLE
Using a socket with phpredis results in strict type error

### ISSUE THREAD

**Issue by simitter** [snc/SncRedisBundle#641]
Hi,

using a socket with phpredis results in a strict type error for the port argument.

```yaml
snc_redis:
    clients:
        default:
            type:    phpredis
            alias:   default
            dsn:     'redis:///run/redis/redis.sock'
            logging: false
```

```
Redis::connect(): Argument #2 ($port) must be of type int, null given
```

Phpredis version: 5.3.4
