### ISSUE TITLE
Fail authentication with sentinel

### ISSUE THREAD

**Issue by JellyBellyDev** [snc/SncRedisBundle#642]
Hi!

My test it's with: 
- `php`: 8.1
- `synfony/symfony`: 6.0.2
- `predis/predis`: 1.1.9
- `snc/redis-bundle`: 4.0.1

I was inspired by this example configuration:
```
snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn:
                - redis://[myhost01]:26379
                - redis://[myhost02]:26379
                - redis://[myhost03]:26379
            logging: '%kernel.debug%'
            options:
                replication: sentinel
                service: [mymaster]
                parameters:
                    database: 1
                    password: [mypass]
```

I applied the configs for my sentinel cluster and I receive the following error message in Symfony Profiler:
```
SENTINEL slaves [mymaster]
An error occured: NOAUTH Authentication required.
```
and 
```
SENTINEL get-master-addr-by-name [mymaster]
An error occured: NOAUTH Authentication required.
```
where `[mymaster]` it's the my service name.

My configs are correct! I tried my configs with other software in node and works.

Can I do something to help debug and figure out how it doesn't work?

Thank you
