### ISSUE TITLE
Warning: Declaration should be compatible with Redis...

### ISSUE THREAD

**Issue by mabzzz** [snc/SncRedisBundle#644]
Hello,

I'm using snc/redis-bundle with phpredis (not predis) and I got the following warning messages :

```
PHP Warning:  Declaration of Redis_ca5fc0f::bitop($operation, $ret_key, $key) should be compatible with Redis::bitop($operation, $ret_key, $key, ...$other_keys) in /var/www/app/var/cache/prod/Container8id9jp2/Redis_ca5fc0f.php on line 3
PHP Warning:  Declaration of Redis_ca5fc0f::blPop($key, $timeout_or_key) should be compatible with Redis::blPop($key, $timeout_or_key, ...$extra_args) in /var/www/app/var/cache/prod/Container8id9jp2/Redis_ca5fc0f.php on line 3
PHP Warning:  Declaration of Redis_ca5fc0f::brPop($key, $timeout_or_key) should be compatible with Redis::brPop($key, $timeout_or_key, ...$extra_args) in /var/www/app/var/cache/prod/Container8id9jp2/Redis_ca5fc0f.php on line 3
PHP Warning:  Declaration of Redis_ca5fc0f::delete($key) should be compatible with Redis::delete($key, ...$other_keys) in /var/www/app/var/cache/prod/Container8id9jp2/Redis_ca5fc0f.php on line 3
PHP Warning:  Declaration of Redis_ca5fc0f::exists($key) should be compatible with Redis::exists($key, ...$other_keys) in /var/www/app/var/cache/prod/Container8id9jp2/Redis_ca5fc0f.php on line 3
PHP Warning:  Declaration of Redis_ca5fc0f::hDel($key, $member) should be compatible with Redis::hDel($key, $member, ...$other_members) in /var/www/app/var/cache/prod/Container8id9jp2/Redis_ca5fc0f.php on line 3
PHP Warning:  Declaration of Redis_ca5fc0f::punsubscribe($pattern) should be compatible with Redis::punsubscribe($pattern, ...$other_patterns) in /var/www/app/var/cache/prod/Container8id9jp2/Redis_ca5fc0f.php on line 3
PHP Warning:  Declaration of Redis_ca5fc0f::sDiff($key) should be compatible with Redis::sDiff($key, ...$other_keys) in /var/www/app/var/cache/prod/Container8id9jp2/Redis_ca5fc0f.php on line 3
PHP Warning:  Declaration of Redis_ca5fc0f::sDiffStore($dst, $key) should be compatible with Redis::sDiffStore($dst, $key, ...$other_keys) in /var/www/app/var/cache/prod/Container8id9jp2/Redis_ca5fc0f.php on line 3
PHP Warning:  Declaration of Redis_ca5fc0f::sInter($key) should be compatible with Redis::sInter($key, ...$other_keys) in /var/www/app/var/cache/prod/Container8id9jp2/Redis_ca5fc0f.php on line 3
PHP Warning:  Declaration of Redis_ca5fc0f::sInterStore($dst, $key) should be compatible with Redis::sInterStore($dst, $key, ...$other_keys) in /var/www/app/var/cache/prod/Container8id9jp2/Redis_ca5fc0f.php on line 3
PHP Warning:  Declaration of Redis_ca5fc0f::sRemove($key, $member) should be compatible with Redis::sRemove($key, $member, ...$other_members) in /var/www/app/var/cache/prod/Container8id9jp2/Redis_ca5fc0f.php on line 3
PHP Warning:  Declaration of Redis_ca5fc0f::sUnion($key) should be compatible with Redis::sUnion($key, ...$other_keys) in /var/www/app/var/cache/prod/Container8id9jp2/Redis_ca5fc0f.php on line 3
PHP Warning:  Declaration of Redis_ca5fc0f::sUnionStore($dst, $key) should be compatible with Redis::sUnionStore($dst, $key, ...$other_keys) in /var/www/app/var/cache/prod/Container8id9jp2/Redis_ca5fc0f.php on line 3
PHP Warning:  Declaration of Redis_ca5fc0f::script($cmd) should be compatible with Redis::script($cmd, ...$args) in /var/www/app/var/cache/prod/Container8id9jp2/Redis_ca5fc0f.php on line 3
PHP Warning:  Declaration of Redis_ca5fc0f::unsubscribe($channel) should be compatible with Redis::unsubscribe($channel, ...$other_channels) in /var/www/app/var/cache/prod/Container8id9jp2/Redis_ca5fc0f.php on line 3
PHP Warning:  Declaration of Redis_ca5fc0f::watch($key) should be compatible with Redis::watch($key, ...$other_keys) in /var/www/app/var/cache/prod/Container8id9jp2/Redis_ca5fc0f.php on line 3
PHP Warning:  Declaration of Redis_ca5fc0f::zDelete($key, $member) should be compatible with Redis::zDelete($key, $member, ...$other_members) in /var/www/app/var/cache/prod/Container8id9jp2/Redis_ca5fc0f.php on line 3
PHP Warning:  Declaration of Redis_ca5fc0f::del($key) should be compatible with Redis::del($key, ...$other_keys) in /var/www/app/var/cache/prod/Container8id9jp2/Redis_ca5fc0f.php on line 3
PHP Warning:  Declaration of Redis_ca5fc0f::srem($key, $member) should be compatible with Redis::srem($key, $member, ...$other_members) in /var/www/app/var/cache/prod/Container8id9jp2/Redis_ca5fc0f.php on line 3
PHP Warning:  Declaration of Redis_ca5fc0f::zRem($key, $member) should be compatible with Redis::zRem($key, $member, ...$other_members) in /var/www/app/var/cache/prod/Container8id9jp2/Redis_ca5fc0f.php on line 3
```

Here's my current configuration :
```
snc_redis:
    clients:
        default:
            type: phpredis
            alias: default
            dsn: '%redis_default_host%'
            logging: false # Not compatible with phpredis
        cache:
            type: phpredis
            alias: cache
            dsn: '%redis_cache_host%'
            logging: false # Not compatible with phpredis
            options:
                profile: 2.2
                connection_timeout: 10
                read_write_timeout: 30
        session:
            type: phpredis
            alias: session
            dsn: '%redis_session_host%'
            logging: false # Not compatible with phpredis
    session:
        client: session
        ttl: '%dyg.session.ttl%'
```

And the versions used:
- snc/redis-bundle: 3.6
- php: 7.3.29
- phpredis: 4.2.0
- redis server: 6.0.16

I saw that all issues related to similar errors have been closed but it doesn't look that the problem has been fixed.
Am I the only who keeps getting that ?
