### ISSUE TITLE
Weird execption when clearing cache pool

### ISSUE THREAD

**Issue by wouter-toppy** [snc/SncRedisBundle#649]
Got the issue: 

`Snc\RedisBundle\Client\Predis\Connection\ConnectionWrapper::Snc\RedisBundle\Client\Predis\Connection\{closure}(): Argument #2 ($argument) must be of type string, null given` 

which is located in `vendor/snc/redis-bundle/src/Client/Predis/Connection/ConnectionWrapper.php:125` 

run the command: 
`bin/console cache:pool:clear cache.app` 

Funny part is, that my application is working. and its using caching. but this errors only occurs when you try to clear the cache pool using the command or in code `$cachePool->clear();` 

On a breakpoint on `vendor/snc/redis-bundle/src/Client/Predis/Connection/ConnectionWrapper.php:157`  you can see that the first parameter of the arguments is `null`..  
This is coming from symfony itself the `$cursor` in `vendor/symfony/cache/Traits/RedisTrait.php:423` 

How can we fix this?

![image](https://user-images.githubusercontent.com/40226924/151562713-4dacf382-8028-46c3-ab00-bce068c6bc95.png)

this are my settings: 
```yaml
framework:
    cache:
        app: cache.adapter.redis
        default_redis_provider: snc_redis.cache
                
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler
        storage_factory_id: session.storage.factory.native
        name: stocky_sessid
        cookie_lifetime: 86400 # 1 day
        gc_maxlifetime: 1800 # 30 minutes
        gc_probability: 2 # 2 / 100 = 2% of all requests
        gc_divisor: 100

services:
    # Session handler
    Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler:
        arguments: 
            - '@snc_redis.session'


snc_redis:
    clients:
        cache:
            type: predis
            alias: cache
            dsn: "%env(REDIS_CACHE_DSN)%"
            logging: '%kernel.debug%'
            options:
                prefix: 'stocky:cache:'
        session:
            type: predis
            alias: session
            dsn: "%env(REDIS_SESSION_DSN)%"
            logging: '%kernel.debug%'
            options:
                prefix: 'stocky:session:'


```
