### ISSUE TITLE
RedisCluster::__construct() expects parameter 6 to be string, null given

### ISSUE THREAD

**Issue by Webonaute** [snc/SncRedisBundle#656]
I started to get this error. 

and client is php-redis extension 5.1.1
server has no password.

Any idea what can cause this?

```
[stderr]20:15:41 CRITICAL [console] Error thrown while running command "sonata:admin:setup-acl". Message: "RedisCluster::__construct() expects parameter 6 to be string, null given" ["exception" => TypeError { …},"command" => "sonata:admin:setup-acl","message" => "RedisCluster::__construct() expects parameter 6 to be string, null given"] ["memory_usage" => "63 MB","uid" => "62c7ff6cba3ebe75e20bbd8e35343e7d","version" => "master-f6ed00c-20220311201348-15092","request_id" => null,"env" => "beta"]
[stderr]
[stderr]In PhpredisClientFactory.php line 105:
[stderr]
[stderr] RedisCluster::__construct() expects parameter 6 to be string, null given
```

our config look like this :

```
snc_redis:
  clients:
    default:
      logging: false
      type: phpredis
      alias: default
      dsn:
        - '%cache_host%?alias=master'
      options:
        prefix: 'a-%api_build%_'
        cluster: true
    sessionClient:
      logging: false
      type: phpredis
      alias: sessionClient
      dsn:
        - '%cache_host%?alias=master'
      options:
        prefix: 'sess_'
        cluster: true
    noPrefixClient:
      logging: false
      type: phpredis
      alias: noPrefixClient
      dsn:
        - '%cache_host%?alias=master'
      options:
        cluster: true
```
