### ISSUE TITLE
Cache is still in filesystem

### ISSUE THREAD

**Issue by krajcikondra** [snc/SncRedisBundle#665]
Hi,

I switch cache of pools to redis, delete var/cache folder and start my application. Now, whan I see to var/cache folder a see folder var/cache/dev/pools/system/  which contains folders.

It seems be weird because I want store pools cache to redis.

in my serveces.yaml

```
snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: "%env(REDIS_DSN)%"
        cache:
            type: predis
            alias: cache
            dsn: "%env(REDIS_DSN)%"
            logging: false
```

my cache.yaml

```
framework:
    cache:
        app: cache.adapter.redis
        default_redis_provider: "%env(REDIS_DSN)%"

        pools:
            doctrine.result_cache_pool:
                adapter: cache.adapter.redis

            doctrine.system_cache_pool:
                adapter: cache.adapter.redis

```

Do I something bad?

Thanks in advance
