### ISSUE TITLE
The factory can only instantiate \Redis|\RedisCluster classes: "Redis" asked

### ISSUE THREAD

**Issue by numediaweb** [snc/SncRedisBundle#680]
I  have a command that checks for routes and generates some type script routes.. But it fails because of this bundle and gives the following error:

```
In PhpredisClientFactory.php line 71:

  The factory can only instantiate \Redis|\RedisCluster classes: "Redis" asked
```

About the project:

```shell
-------------------- ---------------------------------
  Symfony
 -------------------- ---------------------------------
  Version              5.4.15
  Long-Term Support    Yes
  End of maintenance   11/2024 (in +736 days)
  End of life          11/2025 (in +1101 days)
 -------------------- ---------------------------------
  Kernel
 -------------------- ---------------------------------
  Type                 App\Kernel
  Environment          local
  Debug                true
  Charset              UTF-8
  Cache directory      ./var/cache/local (12.9 MiB)
  Build directory      ./var/cache/local (12.9 MiB)
  Log directory        ./var/log (553 KiB)
 -------------------- ---------------------------------
  PHP
 -------------------- ---------------------------------
  Version              8.0.25
  Architecture         64 bits
  Intl locale          en_US_POSIX
  Timezone             UTC (2022-11-25T12:10:09+00:00)
  OPcache              true
  APCu                 true
  Xdebug               false
 -------------------- ---------------------------------
```
Here's the `predis/predis` package info

```
composer show predis/predis                                                                        57356-actions-groupées-volontaires ● ↑1  12:11:53
name     : predis/predis
descrip. : Flexible and feature-complete Redis client for PHP and HHVM
keywords : nosql, predis, redis
versions : * v1.1.10
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
homepage : http://github.com/predis/predis
source   : [git] https://github.com/predis/predis.git a2fb02d738bedadcffdbb07efa3a5e7bd57f8d6e
dist     : [zip] https://api.github.com/repos/predis/predis/zipball/a2fb02d738bedadcffdbb07efa3a5e7bd57f8d6e a2fb02d738bedadcffdbb07efa3a5e7bd57f8d6e
path     : /var/www/service-civique/vendor/predis/predis
names    : predis/predis

support
issues : https://github.com/predis/predis/issues
source : https://github.com/predis/predis/tree/v1.1.10

autoload
psr-4
Predis\ => src/

requires
php >=5.3.9

requires (dev)
phpunit/phpunit ~4.8

suggests
ext-curl Allows access to Webdis when paired with phpiredis
ext-phpiredis Allows faster serialization and deserialization of the Redis protocol
```

**Comment by ostrolucky** [comment]
PhpredisClientFactory has nothing to do with predis. What's the version of this bundle installed and what's the content of snc_redis config?

**Comment by numediaweb** [comment]
Thanks @ostrolucky for the quick replay :)
Here's the config:
```Yaml
snc_redis:
    clients:
        default:
            type: phpredis
            alias: default
            dsn: "%env(REDIS_URL)%"
        session:
            type: predis
            alias: session
            dsn: "%env(REDIS_URL)%/1"

framework:
    session:
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        cookie_lifetime: 604800 # 1 week
        gc_maxlifetime: 604800 # 1 week
    cache:
        app: cache.adapter.redis
        # app cache from client config as default adapter/provider
        default_redis_provider: snc_redis.default
        pools:
            doctrine.result_cache_pool:
                adapter: cache.adapter.redis
                default_lifetime: 604800 # 1 week
            doctrine.system_cache_pool:
                adapter: cache.adapter.redis
                default_lifetime: 604800 # 1 week

# sessions
services:
    Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler:
        arguments: ['@snc_redis.session']

doctrine:
    orm:
        auto_generate_proxy_classes: false
        metadata_cache_driver:
            type: pool
            pool: doctrine.system_cache_pool
        query_cache_driver:
            type: pool
            pool: doctrine.system_cache_pool
        result_cache_driver:
            type: pool
            pool: doctrine.result_cache_pool
```

And this package info (both installed on dev environment ):

```
composer show snc/redis-bundle                                                                     57356-actions-groupées-volontaires ● ↑1  12:25:02
name     : snc/redis-bundle
descrip. : A Redis bundle for Symfony
keywords : nosql, redis, symfony
versions : * 4.3.2
type     : symfony-bundle
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
homepage : https://github.com/snc/SncRedisBundle
source   : [git] https://github.com/snc/SncRedisBundle.git 5797249b34fce59880227221c99606132676d920
dist     : [zip] https://api.github.com/repos/snc/SncRedisBundle/zipball/5797249b34fce59880227221c99606132676d920 5797249b34fce59880227221c99606132676d920
path     : /var/www/service-civique/vendor/snc/redis-bundle
names    : snc/redis-bundle

support
issues : https://github.com/snc/SncRedisBundle/issues
source : https://github.com/snc/SncRedisBundle/tree/4.3.2

autoload
psr-4
Snc\RedisBundle\ => src/

requires
php ^7.4 || ^8.0
symfony/framework-bundle ^4.4 || ^5.3 || ^6.0
symfony/http-foundation ^4.4 || ^5.3 || ^6.0
symfony/service-contracts >=1.0
symfony/var-dumper ^4.4 || ^5.3 || ^6.0

requires (dev)
doctrine/annotations ^1.13
doctrine/coding-standard ^10.0
ext-pdo_sqlite *
ext-redis *
friendsofphp/proxy-manager-lts ^1.0.6
monolog/monolog *
phpunit/phpunit ^8.5 || ^9.5
predis/predis >=1.1
symfony/browser-kit ^4.4 || ^5.3 || ^6.0
symfony/cache ^4.4 || ^5.3 || ^6.0
symfony/console ^4.4 || ^5.3 || ^6.0
symfony/dom-crawler ^4.4 || ^5.3 || ^6.0
symfony/filesystem ^4.4 || ^5.3 || ^6.0
symfony/phpunit-bridge ^6.0
symfony/profiler-pack ^1.0
symfony/proxy-manager-bridge ^4.4 || ^5.3 || ^6.0
symfony/stopwatch ^4.4 || ^5.3 || ^6.0
symfony/twig-bundle ^4.4 || ^5.3 || ^6.0
symfony/yaml ^4.4 || ^5.3 || ^6.0
vimeo/psalm ^4.13

suggests
monolog/monolog If you want to use the monolog redis handler.
predis/predis If you want to use predis.
symfony/console If you want to use commands to interact with the redis database
symfony/proxy-manager-bridge If you want to lazy-load some services

conflicts
ext-redis <5.3
predis/predis <1.1 || >=2.0
```

**Comment by numediaweb** [comment]
I found the culprit :)
In the environment where this command is executed, redis is not installed: this creates the above error...
The solution is to change my config and switch `phpredis` to `predis`:
```yaml
snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: "%env(REDIS_URL)%"
        session:
            type: predis
            alias: session
            dsn: "%env(REDIS_URL)%/1"
```
