### ISSUE TITLE
Broken basic configuration without sentinel/replication in `v4.4.0`

### ISSUE THREAD

**Issue by p4veI** [snc/SncRedisBundle#684]
Hello, while updating the snc-redis library in my project which uses basic predis configuration for this bundle, the configuration I'm using fails with `InvalidArgumentException`:
```
Values evaluating to FALSE are not accepted for `replication`
```

My configuration looks like this:
```
snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: '%env(REDIS_DSN)%'
```

I believe the issue is caused by the change in config options for the newly added sentinel support in the `Configuration.php` file https://github.com/snc/SncRedisBundle/commit/6f654e43ed9042e4ca53496e7a2b109fc6749ae0

We're not using replication so I believe it's impossible for me to adjust the config so the value can be passes. Neither the above config nor including the following works.
```
options:
  replication: false
```
