### ISSUE TITLE
For the type 'predis', the option 'parameters' is not working (neither 'database' nor 'password')

### ISSUE THREAD

**Issue by ywcdiao** [snc/SncRedisBundle#689]
Hi, I found a problem when using the option 'parameters' for the type 'predis'

Here is the config:
```yaml
snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: 'redis://localhost:6379'
            options:
                parameters:
                    database: 11
                    password: pass
```

But the parameters are not working properly. It is working only if the 'database' or 'password' is passed in the 'dsn'.
Could you please help check?

What about change the code here?
https://github.com/snc/SncRedisBundle/blob/master/src/Factory/PredisParametersFactory.php#L27
```php
$dsnOptions     = array_merge($defaultOptions, $options, $dsnOptions, $options['parameters']);
```

Kind regards,
Weichao
