### ISSUE TITLE
predis and phpredis prefixes.

### ISSUE THREAD

**Issue by stephpy** [snc/SncRedisBundle#69]
Hi, 

At this moment, we can define prefix on phpredis connection or predis but it's not work (at least for phpredis).

I guess we could only use:

```
snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: redis://localhost
            options:
                prefix: XYZ
```

And then remove prefix notion on session.handler and namespace notion on doctrine.

`phpredis` provides an option to define a prefix: https://github.com/nicolasff/phpredis#setoption
`predis` too (i'm not sure it's implemented yet on this bundle).

Any thoughts ?
