### ISSUE TITLE
replication option: predis/predis v2 doesn't allow `true`

### ISSUE THREAD

**Issue by Gregoire-M** [snc/SncRedisBundle#692]
I'm updating a project that uses predis and SncRedisBundle with this config:

```
  - Upgrading predis/predis (v1.1.10 => v2.0.3)
  - Upgrading snc/redis-bundle (4.4.1 => 4.5.0)
```

```yaml
snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn:
                - "%env(REDIS_URL)%?alias=master"
                - "%env(REDIS_URL_READ_ONLY)%"
            logging: '%kernel.debug%'
            options:
                replication: true

```

But I get this error when I try to connect to Redis:

```
In Replication.php line 40:

  [InvalidArgumentException]
  Predis\Configuration\Option\Replication expects either a string or a callable value, boolean given


Exception trace:
  at /srv/app/vendor/predis/predis/src/Configuration/Option/Replication.php:40
 Predis\Configuration\Option\Replication->filter() at /srv/app/vendor/predis/predis/src/Configuration/Options.php:103
 Predis\Configuration\Options->__get() at /srv/app/vendor/predis/predis/src/Client.php:125
 Predis\Client::createConnection() at /srv/app/vendor/predis/predis/src/Client.php:61
 ...
```

Indeed, in [predis code](https://github.com/predis/predis/blob/main/src/Configuration/Option/Replication.php#L31-L46), I can see that the value is supposed to be a string (`predis`, `sentinel` or `redis-sentinel`) or a callable.

But SncRedisBundle [forces](https://github.com/snc/SncRedisBundle/blob/master/src/DependencyInjection/Configuration/Configuration.php#L130) me to set `true` or `'sentinel'`.

Am I missing something? Or is there a problem between predis v2 and SncRedisBundle v4.5?
