### ISSUE TITLE
Database parameter is not applied from config

### ISSUE THREAD

**Issue by specdrum-agc** [snc/SncRedisBundle#699]
I have next config:

```
snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsns:
                - '%env(REDIS_DSN)%'
            options:
                parameters:
                    database: 5
```

But database parameter is not applied and data is written to default database.
