### ISSUE TITLE
Setting TTL to session without cookie_lifetime

### ISSUE THREAD

**Issue by MattKetmo** [snc/SncRedisBundle#70]
Hello,

I would like to add the ability to set TTL on Redis session keys, but without having to set the `cookie_lifetime` option of the framework.

The reason is that setting an expiration date on the session cookie could be a bad idea. For instance, a client who have an "early date" (in GMT -- many people change the time of their computer without selecting the right timezone) will not have any session because his browser will consider the cookie expired.

For that reason I prefer to leave the cookie_lifetime to 0. But I still want to set a TTL in redis (for security and storage purposes). As this [StackOverflow](http://stackoverflow.com/a/1270960/696927) comment points out, a "timeout should be implemented on your own", not with `session.gc_maxlifetime` or  `session.cookie_lifetime`.

So the idea is to add a parameter in the configuration which will override the cookie_lifetime parameter of the framework config. Something like:

```
snc_redis:
    ...
    session:
        client: session
        prefix: foo
        cookie_lifetime: 1440 # override framework.cookie_lifetime for Redis TTL
```

I would like your opinion before implementing this solution.
