### ISSUE TITLE
Master-slave: connection problem

### ISSUE THREAD

**Issue by krajcikondra** [snc/SncRedisBundle#701]
Hi,

I am trying configure my redis as master-slave. I am using snc/redis-bundle v4.4.2. This is my config

.env
```
REDIS_MASTER_DSN=tcp://redis-primary?alias=master
REDIS_SLAVE_DSN=tcp://redis-replica

```

services.yaml
```
snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn:
                - "%env(REDIS_MASTER_DSN)%"
                - "%env(REDIS_SLAVE_DSN)%"
            options:
                replication: true
        cache:
            type: predis
            alias: cache
            dsn:
                - "%env(REDIS_MASTER_DSN)%"
                - "%env(REDIS_SLAVE_DSN)%"
            logging: false
            options:
                replication: true
```

I have chat in my webpage and chat seems working, but when I start my websocket server (gos/web-socket-bundle) in debug mode I see following:

```
[2023-04-18T09:02:58.541377+02:00] cache.WARNING: Failed to save key "dd82a9ad8b54ea8cc6e1ae68bed5bb71" of type Doctrine\ORM\Query\ParserResult: php_network_getaddresses: getaddrinfo for failed: Name or service not known [tcp://:6379] {"key":"dd82a9ad8b54ea8cc6e1ae68bed5bb71","exception":"[object] (Predis\Connection\ConnectionException(code: 0): php_network_getaddresses: getaddrinfo for failed: Name or service not known [tcp://:6379] at /var/www/html/vendor/snc/redis-bundle/src/Client/Predis/Connection/ConnectionWrapper.php:169)\n[previous exception] [object] (Predis\Connection\ConnectionException(code: 0): php_network_getaddresses: getaddrinfo for failed: Name or service not known [tcp://:6379] at /var/www/html/vendor/predis/predis/src/Connection/AbstractConnection.php:155)","cache-adapter":"Symfony\Component\Cache\Adapter\RedisAdapter","tracy_filename":"exception--2023-04-18--81ded002fa.html"} []
09:02:58 WARNING [cache] Failed to save key "dd82a9ad8b54ea8cc6e1ae68bed5bb71" of type Doctrine\ORM\Query\ParserResult: php_network_getaddresses: getaddrinfo for failed: Name or service not known [tcp://:6379] ["key" => "dd82a9ad8b54ea8cc6e1ae68bed5bb71","exception" => Predis\Connection\ConnectionException^ { …},"cache-adapter" => "Symfony\Component\Cache\Adapter\RedisAdapter","tracy_filename" => "exception--2023-04-18--81ded002fa.html"]
```

It looks like some problem with configuration because **tcp://:6379** is not correctly. But where I can set this configuration?

**Comment by krajcikondra** [comment]
No, It is connection problem. I cant connect to server because there is bad host

`tcp://:6379`

I need set there etc. something like this

`tcp://redis-primary?alias=master`

But I dont know how

**Comment by ostrolucky** [comment]
follow our docs please

**Comment by krajcikondra** [comment]
I follow docs. When I look to example in [docs](https://github.com/snc/SncRedisBundle/tree/4.4.2/docs)

```
snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn:
                - redis://master-host?alias=master
                - redis://slave-host1
                - redis://slave-host2
            options:
                replication: true
```

And compare with my configuration

```
snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn:
                - "%env(REDIS_MASTER_DSN)%"
                - "%env(REDIS_SLAVE_DSN)%"
            options:
                replication: true
        cache:
            type: predis
            alias: cache
            dsn:
                - "%env(REDIS_MASTER_DSN)%"
                - "%env(REDIS_SLAVE_DSN)%"
            logging: false
            options:
                replication: true

```

I see no difference.
