### ISSUE TITLE
Predis default key name stored in Redis

### ISSUE THREAD

**Issue by danrod7** [snc/SncRedisBundle#705]
Hi, 

I was wondering something about the key stored in redis.
Mine looks like per default like this : NnXrdxiuBQ

```
snc_redis:

    default:
      type: "predis"
      alias: default
      dsn: "%env(REDIS_URL)%"
      options:
        prefix: xxx
```
Given this, it replaces my key per xxxNnXrdxiuBQ

Is there a way to define completely the key in the options ? 
If not, does this key remain the same given any environment ? 
Because I need the full key in order to expire it

Thanks !
