### ISSUE TITLE
Session storage setup

### ISSUE THREAD

**Issue by penfold45** [snc/SncRedisBundle#72]
Hi

I am trying to get redis to store my session data. I have the following configuration 

```
snc_redis:
clients:
    default:
        type: predis
        alias: default
        dsn: redis://localhost
    session:
        type: predis
        alias: session
        dsn: redis://localhost/2
session:
    client: session
    prefix: session_
    use_as_default: true
```

but it does not work i.e there are no keys in database 2 in redis.

I also tried setting 

```
    session:
        storage_id: snc_redis.session.handler
```

but I get the following fatal.

```
ErrorException: Catchable Fatal Error: Argument 1 passed to Symfony\Component\HttpFoundation\Session\Session::__construct() must implement interface Symfony\Component\HttpFoundation\Session\Storage\SessionStorageInterface, instance of Snc\RedisBundle\Session\Storage\Handler\RedisSessionHandler
```

I am using 

```
Symfony 2.1.3
"snc/redis-bundle": "2.1.x-dev",
"predis/predis": "0.8",
```

Any help in the right direction would be very welcome. Thanks
