### ISSUE TITLE
Feature Request: Support for passing DSN as an array in snc-redis configuration

### ISSUE THREAD

**Issue by alexmorbo** [snc/SncRedisBundle#732]
It would be very useful if `snc-redis` supported the ability to pass an array of DSNs directly in the configuration. 

Currently, when using the dsn parameter in the configuration, only a single string is accepted, but passing multiple DSNs as an array would allow for more flexibility, especially when configuring Redis Sentinel.

**Use Case:**
Imagine we have the following environment variable:
```
REDIS_SENTINEL_ADDRS=redis://redis-node-0.redis-headless.redis:26379,redis://redis-node-1.redis-headless.redis:26379,redis://redis-node-2.redis-headless.redis:26379
```
And we want to configure the dsn in the snc-redis configuration like this:
```
dsn:
    - redis://redis-node-0.redis-headless.redis:26379
    - redis://redis-node-1.redis-headless.redis:26379
    - redis://redis-node-2.redis-headless.redis:26379
```

Currently, using `dsn: '%env(csv:REDIS_SENTINEL_ADDRS)%'` results in an error because the configuration expects a single string, not an array of strings.

It would be great if the configuration could accept the environment variable as an array, enabling a more natural way to define the DSNs, especially when using environment variables with multiple Redis Sentinel nodes.

**Desired Behavior:**
Support a configuration that would allow passing multiple DSNs as an array, such as:
```
dsn: '%env(csv:REDIS_SENTINEL_ADDRS)%'
```

Where the environment variable is:

```
REDIS_SENTINEL_ADDRS=redis://redis-node-0.redis-headless.redis:26379,redis://redis-node-1.redis-headless.redis:26379,redis://redis-node-2.redis-headless.redis:26379
```

This would allow a flexible and clean way to pass multiple Redis Sentinel addresses in the configuration, especially when using `.env` or environment variables.

Example:
```
snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: '%env(redis_sentinels:REDIS_SENTINEL_ADDRS)%'
            options:
                replication: sentinel
                service: "%env(REDIS_SENTINEL_MASTER_NAME)%"
                read_write_timeout: "%env(float:REDIS_READ_TIMEOUT)%"
                connection_timeout: "%env(float:REDIS_CONNECTION_TIMEOUT)%"
                parameters:
                    database: "%env(int:REDIS_DATABASE)%"
                    password: "%env(REDIS_PASSWORD)%"
```

This approach would provide cleaner, more flexible configuration management for Redis Sentinel clusters and improve support for multiple Redis nodes.

**Additional Context:**
- The current behavior expects a string, and passing an array results in errors, which could be avoided by allowing an array input for the dsn parameter.
- This feature would align well with existing Symfony functionality where environment variables can be automatically converted into arrays, lists, or strings depending on the context.
