### ISSUE TITLE
Error when defining multiple redis servers in a cluster

### ISSUE THREAD

**Issue by ronnylt** [snc/SncRedisBundle#78]
I have a redis cluster (implementing client-side sharding). The configuration is something like the following:

```
snc_redis:
    clients:
        lock:
            type: predis
            alias: lock
            dsn:
                - redis://localhost/1?weight=10
                - redis://localhost/2?weight=5
                - redis://localhost/3?weight=3
                - redis://localhost/4?weight=3

```

After activating this, I am getting the following error:

```
  [Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]  
  The service definition "snc_redis.client.lock1_options" does not exist.   
```

The bug seems to be in the LoggingPass compiler pass. 

I tried to fix the bug and make a PR, but do not understand what is the purpose of the compiler pass and how to handle Loggable connections when multiple servers are defined.

Could you please give some insights so that I could work on a patch.

Thanks.
