### ISSUE TITLE
some times session wont save automatically 

### ISSUE THREAD

**Issue by scourgen** [snc/SncRedisBundle#79]
my conf:

```
snc_redis:
    clients:
        default:
            type: phpredis
            alias: default
            dsn: redis://127.0.0.1:6379/1
            logging: %kernel.debug%
        cache:
            type: phpredis
            alias: cache
            dsn: redis://127.0.0.1:6379/2
        session:
            type: phpredis
            alias: session
            dsn: redis://127.0.0.1:6379/3
    session:
        ttl: 3600
        client: session
        prefix: sc_session
        use_as_default: true
framework:
    session:         ~
```

my controller:

```
    /**
     * @Route("/about",name="aboutMe")
     * @Template()
     */
    public function meAction()
    {
        $v=rand(1,9999);
        ld($v);
        $this->get('session')->set('aaaaaaaaa',$v);
        return new \Symfony\Component\HttpFoundation\RedirectResponse('/advice');
    }

    /**
     * @Route("/advice",name="aboutAdvice")
     * @Template()
     */
    public function adviceAction()
    {
        ld($this->get('session')->get('aaaaaaaaa'));
        return array('title' => 'aaa');
    }
```

so what I did is:
1.generate a random number on page A
2.dump the number
3.Save the number into session on page A
4.redirect to Page B
5.dump the number which has been saved into session on page A

Normally, I will get 2 same number on page A and page B

but,some times, I will get the different number on Page B which has been save on last turn on Page A.

I guess the problem is because the save function of session hasn't been called automatically.
