### ISSUE TITLE
Client object type varies based on symfony environment

### ISSUE THREAD

**Issue by jkm9000** [snc/SncRedisBundle#90]
Not sure if this is expected behavior, something I am doing wrong, or what... I have a service where I inject redis and when it is in dev mode the object is of type \Snc\RedisBundle\Client\Phpredis\Client but in prod mode it is of type \Redis. So I can't use type hinting in the service constructor.

My configs are below:

```
    snc_redis:
        clients:
            cache:
                type: phpredis
                alias: cache
                dsn: redis://localhost
                logging: %kernel.debug%
        session:
            client: cache
            prefix: sessions
            use_as_default: true

acme.teams_recent:
    class: Acme\TeamBundle\Service\RecentTeams
    arguments: [@snc_redis.cache]
```
