### ISSUE TITLE
Register Custom Command

### ISSUE THREAD

**Issue by borisguery** [snc/SncRedisBundle#92]
Hi,

[Predis](https://github.com/nrk/predis) library provides the ability to [define custom (scripted) commands](https://github.com/nrk/predis#abstraction-for-handling-lua-scripts-as-plain-redis-commands).

From the documentation it is needed to do:

``` php
$client->getProfile()->defineCommand('lpushrand', 'ListPushRandomValue');
```

Obviously, this is not straight-forward in the context of a Symfony2 application.

I couldn't find any trace in the bundle code to support this, and if I'm right I would be happy to implement it myself to allow to define commands in configuration.

I'm just starting with Redis and friends, but a configuration could look like:

``` yml
snc_redis:
  clients:
    default:
      type: predis
      alias: default
      dsn: redis://localhost
      custom_commands:
        lpushrand: 
          class: My\Redis\Command\ListPushRandomValue
```

Some questions remain though:
- I dunno about a similar behavior for `phpredis`
- Only per client commands registration allowed

Any feedbacks?

**Comment by TomAdam** [comment]
Old issue, new solution. I implemented this with a compiler as follows:

```php
class RedisCommandPass implements CompilerPassInterface
{
    /**
     * Register custom commands in a profile
     *
     * @param ContainerBuilder $container
     */
    public function process(ContainerBuilder $container)
    {
        if ($container->hasParameter('predis_custom_commands')) {
            $customCommands = $container->getParameter('predis_custom_commands');

            foreach ($customCommands as $profile => $commands) {
                $profileDefinition = $container->getDefinition($profile);
                foreach ($commands as $name => $class) {
                    $profileDefinition->addMethodCall('defineCommand', [$name, $class]);
                }
            }
        }
    }
}
```

The param looks like this:

```yaml
parameters:
    predis_custom_commands:
        snc_redis.client.<client_alias>_profile:
            <command_name>: <fully_qualified_class_name>
```

It would be great if it was possible define a profile class as well as(but exclusively) a profile version for a client. That way we could create custom profiles avoiding the need for the compiler pass and the custom parameters. It solves the "Only per client commands registration allowed" issue in the OP, but only works with Predis.
