### ISSUE TITLE
Attempting to connect during assets:install

### ISSUE THREAD

**Issue by ornj** [snc/SncRedisBundle#97]
When I call `app/console assets:install ...`, an attempt is made to connect to the Redis server, but at this stage of my deployment process the web and caching servers aren't connected. I'm not sure what reason is there for there to be any connection made when running that command but by removing `metadata_cache` from my config I was able to execute the command.

``` yaml
snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: %redis_dsn%
        cache:
            type: predis
            alias: cache
            dsn: %redis_doctrine_dsn%
            options:
                profile: 2.2
                connection_timeout: 10
                read_write_timeout: 30
    doctrine:
#        metadata_cache:
#            client: cache
#            entity_manager: default
        result_cache:
            client: cache
            entity_manager: default
            namespace: "dcrc:"
        query_cache:
            client: cache
            entity_manager: default
```
